### ISSUE TITLE
Fails on Yosemite

### ISSUE THREAD

**Issue by hagedose** [yujitach/MenuMeters#10]
Perhaps this is to be expected, but I didn't notice a warning: I tried to install this version on Yosemite, but the SysPref fails to open. The following is logged to Console.app:

Oct  5 13:47:06 xxx.rrz.uni-koeln.de System Preferences[81876]: Failed to connect (memPagerateColor) outlet from (MenuMetersPref) to (NSColorWell): missing setter or instance variable
Oct  5 13:47:06 xxx.rrz.uni-koeln.de System Preferences[81876]: Failed to connect (memPagerateColorLabel) outlet from (MenuMetersPref) to (NSTextField): missing setter or instance variable
Oct  5 13:47:06 xxx.rrz.uni-koeln.de System Preferences[81876]: ### com.ragingmenace.MenuMeters instantiatePrefPaneObject exception:*** -[NSURL initFileURLWithPath:]: nil string parameter

**Comment by yujitach** [comment]
It should work on Yosemite. My version has the bundle identifier *com.yujitach.MenuMeters* not *com.ragingmenace.MenuMeters*, so I'm pretty sure that the previous version wasn't completely removed. Could you try removing old MenuMeters.prefPane from ~/Library/PreferencePanes or /Library/PreferencePanes/ and installing the new version again?

**Comment by hagedose** [comment]
Sorry, I'm currently upgrading the Mac in question to El Capitán. Another Mac with Yosemite failed to load the PrefPane initially, but now it's working. Thanks for your help!

**Comment by duffyjp** [comment]
As an FYI: "Me too."  Pref Pane loads installs fine, but doesn't actually do anything.  Works fine in El Capitan.  Tried removing it, reinstalling, rebooting etc.  
![screen shot 2015-10-28 at 10 39 05 am](https://cloud.githubusercontent.com/assets/382216/10793772/4794bdf6-7d60-11e5-81e7-cbe7c2af7a58.png)

**Comment by yujitach** [comment]
On Yosemite, please re-install the original MenuMeters.
