### ISSUE TITLE
Page-in and page-out colors can't be edited.

### ISSUE THREAD

**Issue by yujitach** [yujitach/MenuMeters#101]
why don’t the pagin and pageout colors allow editing. I think this is just an oversight? Since they are the most jarring colors, these are the most important to be able to edit. 

(I'm posting a request in an email I received.)

**Comment by mikezs** [comment]
I've also got this issue on 1.9.7 macOS 10.14.4

**Comment by yujitach** [comment]
I believe it's editable in the latest version, although I don't know when I changed the code...
