### ISSUE TITLE
menumeter uses huge amount of temporary diskspace

### ISSUE THREAD

**Issue by glenndk** [yujitach/MenuMeters#103]
Yesterday I started a scan with Sophos Home Premium (bought Premium yesterday) (the Sophos Home have been installed for about a year). The scan continued today. Both yesterday and today Sierra complained about missing disk space multiple times (Normal disk scenario - plenty of diskspace: $ df -h /dev/disk0s2 335Gi   70Gi  265Gi). this forced a logout of my account and when I logged in, everything was fine.

After some time where Sophos Home was busy scanning, Sierra complained about missing disk space again.

I found this just before logout - my assumption is that menumeter has consumed a lot of diskspace: "292Gi":
$ df -h
...
/dev/disk0s2 335Gi   70Gi  265Gi    21% 1455863 4293511416    0%   /
...
/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app  335Gi  292Gi   42Gi    88% 1459588 4293507691    0%   /private/var/folders/k3/ft3dymg16vvc_33qyqrg6gfc0000gn/T/AppTranslocation/B19C7FBE-3012-4E97-BB97-24C55973ED98
$

The disk icon Command-I window also shows less and less free disk space.

-

In Users & groups, menumeter was a startup item four times. Why not just one time?

After deleting the four menumeter startup item it seems to work fine.

Now:

$ df -h
...
/dev/disk0s2 335Gi   70Gi  264Gi    21% 1455666 4293511613    0%   /
...
/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app 335Gi   70Gi  264Gi    21% 1455647 4293511632    0%   /private/var/folders/k3/ft3dymg16vvc_33qyqrg6gfc0000gn/T/AppTranslocation/FEC59F29-F790-4947-BA65-372BF594D0AD
$

**Comment by yujitach** [comment]
I believe that it's just that `df` shows a miscalculated used diskspace for the volume mounted by the App Translocation mechanism, and that menumeter does not actually use any temporary diskspace. See #41 for details.

**Comment by glenndk** [comment]
sign that the df-numbers are true:

applications shut by Sierra

Sierra complain about missing swap-space

The user is logout.
