### ISSUE TITLE
menumeter uses huge amount of temporary diskspace 2

### ISSUE THREAD

**Issue by glenndk** [yujitach/MenuMeters#104]
(#103 was closed before I could respond)

Signs that the df-numbers are true:

applications shut down by Sierra

Sierra complain about missing swap-space

The user (my account) was logout.

(this happened at least three times)

-

Yesterday I started a scan with Sophos Home Premium (bought Premium yesterday) (the Sophos Home have been installed for about a year). The scan continued today. Both yesterday and today Sierra complained about missing disk space multiple times (Normal disk scenario - plenty of diskspace: $ df -h /dev/disk0s2 335Gi 70Gi 265Gi). this forced a logout of my account and when I logged in, everything was fine.

After some time where Sophos Home was busy scanning, Sierra complained about missing disk space again.

I found this just before logout - my assumption is that menumeter has consumed a lot of diskspace: "292Gi":
$ df -h
...
/dev/disk0s2 335Gi 70Gi 265Gi 21% 1455863 4293511416 0% /
...
/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app 335Gi 292Gi 42Gi 88% 1459588 4293507691 0% /private/var/folders/k3/ft3dymg16vvc_33qyqrg6gfc0000gn/T/AppTranslocation/B19C7FBE-3012-4E97-BB97-24C55973ED98
$

The disk icon Command-I window also shows less and less free disk space.

In Users & groups, menumeter was a startup item four times. Why not just one time?
(#103 was closed before I could respond)

Signs that the df-numbers are true:

applications shut down by Sierra

Sierra complain about missing swap-space

The user is logout.

.

After deleting the four menumeter startup item it seems to work fine.

Now:

$ df -h
...
/dev/disk0s2 335Gi 70Gi 264Gi 21% 1455666 4293511613 0% /
...
/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app 335Gi 70Gi 264Gi 21% 1455647 4293511632 0% /private/var/folders/k3/ft3dymg16vvc_33qyqrg6gfc0000gn/T/AppTranslocation/FEC59F29-F790-4947-BA65-372BF594D0AD
$

**Comment by yujitach** [comment]
I’m sorry for closing it too early. 

I still think it’s not real: the App Translocation volume is actually just part of the main physical volume. If the main volume says 335Gi 70Gi 265Gi, the App Translocation volume can’t use more than 70Gi....

You see, many people use MenuMeters and don’t see this problem (including me). You used MenuMeters together with Sophos for a long time and you didn’t see the problem. You now upgraded to Sophos Premium with MenuMeters and you find the problem. A more logical conclusion is to blame Sophos Premium, or this particular combination of MenuMeters + Sophos Premium. It’s totally possible that Sophos Premium doesn’t know enough about App Translocation and does a bad thing.

I might be wrong, and I am happy to be proven wrong.  To fix it, I need to know exactly which files are occupying such a large space. Doesn’t Sophos Premium tell you which files are big? You say it’s reproducible. If you encounter it next time, before logging out, please look for the them. It can be done by opening the terminal,  go to /private/var/folders/k3/... shown in the output of df, and looking around.
