### ISSUE TITLE
CPU Percentage value for User and System together (small) are wrong

### ISSUE THREAD

**Issue by marcinlesek** [yujitach/MenuMeters#107]
Hello,

firstly, thanks for creating and maintaining this tool 👏 

I'm think that number on CPU with option `User and System (small text)` shows incorrect values (due to Activity Monitor). 

MenuMeters show about 10% & 10% when Activity Monitor only 3% & 4% - this misrepresentation is about twice bigger than Activity Monitor.

Choosing `Total (medium text)` shows proper value (e.g. 7% when Activity Monitor shows 3% & 4% for User and System).

OS: Mojave `10.14.5`
MenuMeters: `v. 1.9.7`

Best regards,
Marcin

**Comment by MrNilz** [comment]
Hi,

I have similar effects. 
It looks to me that `User and System (small text)` just shows the first core and does not really honor the selction made above about which cores to show `physical cores only`, `Sum of All` etc. 
As soon as it comes to `sum` or `average`, for me, the values shown always corresponendt to the first core.

Thx and best regards
MrNilz

**Comment by yujitach** [comment]
Indeed `sum of all cores` was not respected, and corrected in the latest commit. Should be available in the next release. 

Otherwise I believe the code is OK...  please comment if things are still wrong.
