### ISSUE TITLE
Accessive logging

### ISSUE THREAD

**Issue by RichieB2B** [yujitach/MenuMeters#122]
My Console.app is flooded with MenuMeters logs. Is it really necessary to log every value that is looked up? I'm running version 2.0.0
```
looked up value <private> for key CPUAverageMultiProcs in CFPrefsPlistSource<0x6000018a8900> (Domain: com.ragingmenace.MenuMeters, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No) via CFPrefsSearchListSource<0x6000018a9280> (Domain: com.ragingmenace.MenuMeters, Container: (null))
```

**Comment by yujitach** [comment]
This is not logged by MenuMeters; it's rather done by the system library itself. Every preference access goes through the save/load methods defined here:  https://github.com/yujitach/MenuMeters/blob/3fd5c01f6ff13ce79886d2f8ff46897f4f57a666/Common/MenuMeterDefaults.m#L895 and there's no logging on MenuMeters side. 

In any case these debug info are volatile debug info which are only collected while Console.app is run. On this point, see the documentation https://developer.apple.com/documentation/os/logging?language=objc .  So no resource is wasted.

**Comment by RichieB2B** [comment]
Ok, thanks for clearing that up!
