### ISSUE TITLE
Version 2.0 cuts values

### ISSUE THREAD

**Issue by Erik262** [yujitach/MenuMeters#123]
Hello,

when I'm downloading something in high speed, then my Rx values get cutted off. 
As in the picture shown.
![Screenshot 2019-11-27 at 03 09 05](https://user-images.githubusercontent.com/11977647/69687603-d4053680-10c3-11ea-97d2-2821a7650633.png)

**Comment by yujitach** [comment]
I envy your internet connection, and I agree it’s a bug.

**Comment by yujitach** [comment]
I think I fixed it in the new version 2.0.2, available via auto-update. I tentatively close this issue. If it's not fixed, please reopen it.
