### ISSUE TITLE
MenuMeters Version 2.0.0 hangs on Catalina when started from login items

### ISSUE THREAD

**Issue by asoki** [yujitach/MenuMeters#124]
On macOS Catalina, MenuMeters hangs when started on boot from login items, but works fine when started manually from applications folder.

Steps to reproduce:
1. install MenuMeters and update it to 2.0.0
2. reboot your mac

Actual result:
MenuMeters does not appears on the menu bar.
Hovering the place on the menu bar where MenuMeters should appear, displays a beach ball.
MenuMeters is marked red (not responding) in ActivityMonitor. 

Workaround:
Terminate MenuMeters in ActivityMonitor, start MenuMeters manually from Applications folder and remove the automatically created login-item.

OS: macOS Catalina 10.15.1 (19B88)
HW: MacBookPro mid 2015
MenuMeters: v 2.0.0
Analyze Report: https://gist.github.com/asoki/567db194308b7e04f8fb6521fe626d9d

**Comment by yujitach** [comment]
I think I fixed it in the new version 2.0.2, available via auto-update. I tentatively close this issue. If it's not fixed, please reopen it.
