### ISSUE TITLE
2.0.3 - Enable checkbox in CPU panel is misaligned

### ISSUE THREAD

**Issue by luckman212** [yujitach/MenuMeters#126]
Thank you for the recent updates to MenuMeters! Small nitpick: the Enable checkbox for the CPU pane in v2.0.3 is vertically misaligned for some reason:
![image](https://user-images.githubusercontent.com/1992842/70377094-51a81e00-18de-11ea-8e42-25d53f0a3c03.png)

The other panes are correct:
![image](https://user-images.githubusercontent.com/1992842/70377097-5371e180-18de-11ea-88c9-baf3ff49418b.png)

**Comment by LTC59** [comment]
Is there a direct download of 2.0.3 available?

The update process does work fine so "there is no cow on the ice" as we say here in Sweden. 

Keep up the good work!

**Comment by yujitach** [comment]
@luckman212 Ugh, I made a stupid mistake while rearranging controls in the CPU pane... I will fix it in the next update.

@LTC59 I just made a new release https://github.com/yujitach/MenuMeters/releases/tag/2.0.3 .

**Comment by luckman212** [comment]
@yujitach 👍

**Comment by LTC59** [comment]
Thank you!

**Comment by yujitach** [comment]
This is taken care of in 2.0.4.

**Comment by luckman212** [comment]
Got it - looks good! 👍
