### ISSUE TITLE
Bug: wrong Wi-Fi interface speed

### ISSUE THREAD

**Issue by EddyLB** [yujitach/MenuMeters#128]
When clicking on the network throughput (MenuMeters 1.9.7 and 2.0.3 on Catalina), the displayed Wi-Fi speed is always 54 Mbps on my MacBook Pro (15-inch, 2018) while it should be 300 Mbps as shown in the attached screenshots.

<img width="1138" alt="Screenshot 2019-12-08 at 16 21 39" src="https://user-images.githubusercontent.com/7103032/70391652-cb700280-19d7-11ea-8e70-f68597c8809e.png">

<img width="1136" alt="Screenshot 2019-12-08 at 16 09 50" src="https://user-images.githubusercontent.com/7103032/70391654-cb700280-19d7-11ea-8430-f6fb7aa29505.png">

**Comment by bouscram** [comment]
Funny, but on my end 2012 iMac, this is Network Utility which shows a completely wrong speed... 
;-)

**Comment by yujitach** [comment]
The same problem is discussed in #155 which has more info. So I will close this issue.
