### ISSUE TITLE
Doesn't show CPU temperature on macOS Catalina

### ISSUE THREAD

**Issue by BurgerZ** [yujitach/MenuMeters#137]
MenuMeters version: 2.0.4
Settings for CPU:
![image](https://user-images.githubusercontent.com/1331650/71781064-61994780-2fdb-11ea-9958-95f4171bd8b7.png)

Info shown:
![image](https://user-images.githubusercontent.com/1331650/71781067-6bbb4600-2fdb-11ea-964c-3079fea80894.png)

Mac:
![image](https://user-images.githubusercontent.com/1331650/71781074-8c839b80-2fdb-11ea-9df3-5d61ed122886.png)

CPU for this model is Core i7 4771 (Haswell)

**Comment by macintoshme** [comment]
I too am seeing this behavior on my MacPro.

Xeon X5680

**Comment by gustavopergola** [comment]
Just supporting with more info, I'm also running on macOS Catalina MacbookPro 2017 and it works just fine. 

Infos:
Version: 10.15.2
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Processor: 2,3 GHz Dual-Core Intel Core i5

**Comment by BurgerZ** [comment]
Updated to the latest 10.15.5 and I have temperature now. 
![image](https://user-images.githubusercontent.com/1331650/83964163-932c7c80-a8b3-11ea-9cef-d756a0eb535e.png)
