### ISSUE TITLE
Bug in Network "Display this interface"

### ISSUE THREAD

**Issue by Devaria** [yujitach/MenuMeters#14]
Having several network connections like ethernet, Wifi, etc. my primary interface if the wrong one. Selecting from the menu "Display this interface" seems to do nothing for the network menu item.

**Comment by yujitach** [comment]
Hmm, do you know if the bug was present in the previous version for Yosemite and before?

**Comment by AJLindberg** [comment]
This is a new bug, it worked before el capitan. 

It should be easy to test, all macs should have at least two interfaces. When on WIFI and I select ethernet as my primary interface, I would expect the network graph to go to zero since I'm not connected to an ethernet cable. but MenuMeters keeps showing the WIFI interface...

**Comment by easye** [comment]
This bug seems to intermittently effect me as well.

**Comment by simondrummond** [comment]
I just upgraded to El Capitan and loaded the new version. I see data available when you click the monitor, but when I try to select the WiFi, it will not display. 
This worked on all the previous OS X versions.

**Comment by fibaan** [comment]
When signing in to a VPN network the throughput goes to inactive as well (the connection works fine), and switching the interface to the VPN one doesn't work either. I guess same problem as described above, switching interfaces simply doesn't work.

**Comment by coolboiime** [comment]
It's a bug with the original source code. This happened when Yosemite was released.

**Comment by cbrinker** [comment]
Is there a good workaround for this problem?

**Comment by fibaan** [comment]
Yes, select the following option at the System Preferences - Menu Meters - Network tab:
"Display prefers interface: Wi-Fi (en0)"

That way Menu Meters will display everything that goes through the Wi-Fi interface, VPN included.

**Comment by yujitach** [comment]
I think this is working now...
