### ISSUE TITLE
Icon is active in dock

### ISSUE THREAD

**Issue by xtenduke** [yujitach/MenuMeters#140]
Is there a reason for the recent change to add a app icon?
It now sits in the dock as recently opened application after closing the prefpane

Why not use `NSApplicationActivationPolicyAccessory` so we don't get this icon hanging around

![image](https://user-images.githubusercontent.com/5002212/71806092-c84a5e00-30cc-11ea-881e-a9c7aac05487.png)

**Comment by yujitach** [comment]
It does use `NSApplicationActivationPolicyAccessory` to hide the Dock icon and the menu bar, unless the configuration panel is shown.  When the config pane is shown, the Dock icon is intentionally shown, just to make sure.

Also, at least on my Mac, the Dock icon does not remain in the list of the recently opened  applications in the Dock, even when one quits MenuMeters while the config pane is shown. So I can't reproduce the behavior you mention.

**Comment by xtenduke** [comment]
This is due to macos functionality in dock 'Show recent applications in Dock'
Closing
