### ISSUE TITLE
wrong number of cores calculation 

### ISSUE THREAD

**Issue by cattyhouse** [yujitach/MenuMeters#142]
on my i5-8400 6 cores, when cpu runs at 100%  via
`for i in {1..10} ; do yes > /dev/null & ; done`
- [ x ] `the average of all cores` is always showing 83%, **NOT Correct**
- [ x ] `the sum of all cores` is always showing 500%, **NOT Correct**
- [ √ ] the rest 3 options are ok, they show correct 6 "100%"s, **Correct**

so i think the calculation of core was not correct, version 2.0.4

**Comment by cattyhouse** [comment]
Thanks for the fix, will you release a new version soon?

**Comment by yujitach** [comment]
Should be available via the auto update now. Also, you don't need to thank me; it was fixed by @macmaxbh .
