### ISSUE TITLE
Catalina: Doesn't properly switches font color on Auto Darkmode

### ISSUE THREAD

**Issue by mcr-ksh** [yujitach/MenuMeters#145]
When the system automatically switches to dark mode, the font keeps it's color. This will make the CPU status for me invisible.

**Comment by tmagma** [comment]
Hi! Same problem here. But If I check and uncheck CPU display it corrects (not when switching).  Thank you!

**Comment by vannelli2000** [comment]
I have seen the same problem and it does correct itself when checking and unchecking the CPU display.

**Comment by skyfaller** [comment]
I've just been quitting and reopening Menumeters as a workaround. If you hit cmd+Q while clicking on one of the pulldown menus, it will quit Menumeters, and then you can use Spotlight to quickly open it again.

Still interested in a real fix. Does anyone know why this is happening?

**Comment by GerardDirks** [comment]
Same issue here. Bug reported 4 Months ago. The is one of the core function of manometers and when it show the CPU Speed at the wrong color it is frustrating.

**Comment by yujitach** [comment]
In a recent commit I fixed one instance of this bug mentioned in #159 . Unfortunately this bug needs to be fixed one by one for each text and/or graphics element. Could each one of you post the screenshot where the bug shows up?

**Comment by GerardDirks** [comment]
Hello

The Version 2.0.6 solved some issues! The change to the Dark Mode hasn't been fix for my system (MacBookPro16 with 10.15.4), maybe it works on other system combinations?

**Comment by yujitach** [comment]
Dear @GerardDirks , please **do** attach the screenshot of the bug you found! Otherwise I don’t know where to fix!!

**Comment by GerardDirks** [comment]
We have now Daytime 9 hour AM, the color of the CPU Usage is White instead of Black (Right to the CPU Temp)


—————————————————————————————————
Dipl. Ing. Gérard Dirks
Speerstrasse 9
CH-8738 Uetliburg (SG), Switzerland
Tel.: +41-44-515 25 70 Fax.: +41-44-515 25 77, GSM.: +41-79-400 39 09
E-Mail: gerard@dirks.ch
—————————————————————————————————

**Comment by yujitach** [comment]
Uh, the release 2.0.6 I uploaded about a day ago didn't actually fix the dark mode issue I intended, due to my stupid last minute change. I made 2.0.6.1 available via auto-update, which hopefully fix your problem too. Could you try updating the app?

**Comment by skyfaller** [comment]
![menumeters1](https://user-images.githubusercontent.com/80093/80916188-31617b80-8d25-11ea-82f3-c372c7b7cc18.png)
![menumeters2](https://user-images.githubusercontent.com/80093/80916189-31fa1200-8d25-11ea-9519-74a4160c2c53.png)
Here are a couple of screenshots from before your latest updates, sorry I was slow!

It looks like you've fixed the paging activity indicator, but not the disk activity menu meter with color arrows.

**Comment by skyfaller** [comment]
![menumeters3](https://user-images.githubusercontent.com/80093/80916379-438fe980-8d26-11ea-8fda-c9fe29168a1b.png)
Here's the disk activity color arrows dividing line disappearing in the latest version 2.0.6.1.

**Comment by GerardDirks** [comment]
Hello

The Version 2.0.6.1 seems to solve the Dark Mode problem!

THX
Gérard
—————————————————————————————————
Dipl. Ing. Gérard Dirks
Speerstrasse 9
CH-8738 Uetliburg (SG), Switzerland
Tel.: +41-44-515 25 70 Fax.: +41-44-515 25 77, GSM.: +41-79-400 39 09
E-Mail: gerard@dirks.ch
—————————————————————————————————

**Comment by mcr-ksh** [comment]
also confirmed from my side. thanks.
