### ISSUE TITLE
Wrong label: Wi-Fi (en0) - Ethernet 54 Mbps

### ISSUE THREAD

**Issue by veldechev** [yujitach/MenuMeters#155]
I wonder why MenuMeters shows my Wi-Fi network as 54 Mbps while I'm connected to 801.11ac 5 GHz router (in fact AC3200 router with up to 1300 Mbps speed per band). Is this just the label text or it reads the speed from elsewhere?

**Comment by luckman212** [comment]
Mine shows up as "11 Mbps". I had a look at the code, but it's above my pay grade to actually fix.  The calculation seems to happen at [MenuMeterNetExtra.m @L408](https://github.com/yujitach/MenuMeters/blob/master/MenuExtras/MenuMeterNet/MenuMeterNetExtra.m#L408). It appears IOKit is returning an incorrect `linkspeed` value.

Seems like another problem (interface type detection) could be solved by grabbing it via [SCNetworkConfiguration](https://developer.apple.com/documentation/systemconfiguration/scnetworkconfiguration) instead of IOKit in [MenuMeterNetConfig.m around @L329](https://github.com/yujitach/MenuMeters/blob/master/MenuExtras/MenuMeterNet/MenuMeterNetConfig.m#L329)

e.g. if you save the below code as `iflist.m` and then compile & run `./iflist` it correctly outputs the Airport interface type as `IEEE80211`:

**compile**
```
clang iflist.m -fmodules -o iflist
```
**iflist.m**:
```
@import Foundation;
@import SystemConfiguration;

int main() {
  CFArrayRef ref = SCNetworkInterfaceCopyAll();
  NSArray* networkInterfaces = (__bridge NSArray *)(ref);
    for(int i = 0; i < networkInterfaces.count; i += 1) {
      SCNetworkInterfaceRef interface = (__bridge SCNetworkInterfaceRef)(networkInterfaces[i]);
      CFStringRef displayName = SCNetworkInterfaceGetLocalizedDisplayName(interface);
      CFStringRef bsdName = SCNetworkInterfaceGetBSDName(interface);
      printf("  name: %s\n  type: %s\nifname: %s\n\n",
             [(NSString *)displayName UTF8String],
             [(NSString *)SCNetworkInterfaceGetInterfaceType(interface) UTF8String],
             [(NSString *)bsdName UTF8String]);
    }
  }
```

I don't know what other method could be used to obtain the correct interface speeds, but the `airport -I` command correctly reports it, so there's an API for it (maybe undocumented?)

@yujitach is this something you've played with?

**Comment by GerardDirks** [comment]
Same Issue here with MBP 16 & 10.15.4. Bug Recognized in the first Version I used (2.0.1)

**Comment by fwenzel** [comment]
FWIW this is broken for more things as well -- my 100MBit Apple USB  ethernet adapter shows as `10 MBit`, and my Belkin gigabit USB-C ethernet adapter shows as `0.0 kbps`

**Comment by GerardDirks** [comment]
The Strange is that the inaccurate Speed Display of the Ethernet only occurred with the WiFi under 10.15. With older systems and  it seems to works fine.
I haven't test it on my MBP 2015 because it hast an older OS X. I am not intend to update this machine to 10.15 because of the ban of 32bit Apps!

**Comment by yujitach** [comment]
This is mostly due to the fact that starting from Catalina IOKit is being revamped, see  https://developer.apple.com/system-extensions/ . As @luckman212 notes, MenuMeters read these info via IOKit, but most probably some of the device drivers are now written in terms of DriverKit, a newer alternative to IOKit. We need to figure out a more modern way to read out the info.

**Comment by fwenzel** [comment]
FWIW it seems like the IOKit information is flaky, it's not inherently a bug in menumeters:
```
    | |   |   |   |     |   +-o IOSkywalkLegacyEthernet  <class IOSkywalkLegacyEthernet, id 0x1000142da, !registered, !matched, active, busy 0 (2 ms), retain 8>
    | |   |   |   |     |   | | {
    | |   |   |   |     |   | |   "IOClass" = "IOSkywalkLegacyEthernet"
    | |   |   |   |     |   | |   "CFBundleIdentifier" = "com.apple.iokit.IOSkywalkFamily"
    | |   |   |   |     |   | |   "IOProviderClass" = "IOSkywalkEthernetInterface"
    | |   |   |   |     |   | |   "IOMACAddress" = <....>
    | |   |   |   |     |   | |   "IOLinkSpeed" = 0
    | |   |   |   |     |   | |   "IOProbeScore" = 0
    | |   |   |   |     |   | |   "AVBControllerState" = 1
    | |   |   |   |     |   | |   "IOMatchCategory" = "IOSkywalkLegacyEthernet"
    | |   |   |   |     |   | |   "IOSelectedMedium" = ""
    | |   |   |   |     |   | |   "IOMinPacketSize" = 64
    | |   |   |   |     |   | |   "IOFeatures" = 4
    | |   |   |   |     |   | |   "CFBundleIdentifierKernel" = "com.apple.iokit.IOSkywalkFamily"
    | |   |   |   |     |   | |   "IOLinkStatus" = 3
    | |   |   |   |     |   | |   "IOMaxPacketSize" = 1518
    | |   |   |   |     |   | |   "IOActiveMedium" = ""
    | |   |   |   |     |   | |   "IOPacketFilters" = {"IONetworkFilterGroup"=275,"IOEthernetWakeOnLANFilterGroup"=0}
    | |   |   |   |     |   | | }
    | |   |   |   |     |   | | 
    | |   |   |   |     |   | +-o en8  <class IOSkywalkLegacyEthernetInterface, id 0x1000142e0, registered, matched, active, busy 0 (2 ms), retain 11>
    | |   |   |   |     |   |   | {
    | |   |   |   |     |   |   |   "IOLocation" = ""
    | |   |   |   |     |   |   |   "IORequiredPacketFilters" = {"IONetworkFilterGroup"=3,"IOEthernetWakeOnLANFilterGroup"=0}
    | |   |   |   |     |   |   |   "BSD Name" = "en8"
    | |   |   |   |     |   |   |   "IOMaxTransferUnit" = 1500
    | |   |   |   |     |   |   |   "IOInterfaceFlags" = 2082
    | |   |   |   |     |   |   |   "IOInterfaceType" = 6
    | |   |   |   |     |   |   |   "IOMediaAddressLength" = 6
    | |   |   |   |     |   |   |   "IOInterfaceState" = 3
    | |   |   |   |     |   |   |   "IOMediaHeaderLength" = 14
    | |   |   |   |     |   |   |   "IOActivePacketFilters" = {"IONetworkFilterGroup"=0,"IOEthernetWakeOnLANFilterGroup"=0}
    | |   |   |   |     |   |   |   "IOInterfaceExtraFlags" = 0
    | |   |   |   |     |   |   |   "IOPrimaryInterface" = No
    | |   |   |   |     |   |   |   "IOInterfaceUnit" = 8
    | |   |   |   |     |   |   |   "IOInterfaceNamePrefix" = "en"
    | |   |   |   |     |   |   |   "IOBuiltin" = No
    | |   |   |   |     |   |   |   "IONetworkData" = {"IONetworkStatsKey"={"Size"=20,"Data"=<0000000000000000000000000000000000000000>,"Access Types"=9},"IOEthernetStatsKey"={"Size"=216,"Data"=<000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>,"Access Types"=9}}
    | |   |   |   |     |   |   | }
    | |   |   |   |     |   |   | 
```

Note that `IOLinkSpeed` is 0.

Interestingly, my wifi is correctly identified.

As at least a workaround, I suggest we remove the label altogether if no value could be determined, as opposed to falling back to a dummy number.

**Comment by yujitach** [comment]
@fwenzel, what does `ifconfig -v` say about the link speed in your case?

On my Catalina mac, IOLinkSpeed of my Airport (either from MenuMeters, or using `ioreg -l`) is 144 Mbps, while the link speed reported by `ifconfig` (and Network Utility.app) is 54Mbs.

**Comment by yujitach** [comment]
Luckily the source code of `ifconfig` is available at https://opensource.apple.com/source/network_cmds/network_cmds-596/ifconfig.tproj/ , so if it gives the "correct" link speed, I can incorporate the relevant code into MenuMeters.

**Comment by fwenzel** [comment]
This is the relevant piece of `ifconfig -v`: 

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 index 4
        eflags=412008c0<ACCEPT_RTADV,TXSTART,ARPLL,NOACKPRI,ECN_ENABLE,FASTLN_ON>
        xflags=1<WOL>
        options=400<CHANNEL_IO>
        ether <...>
        inet6 <...>%en0 prefixlen 64 secured scopeid 0x4 
        inet 10.11.12.248 netmask 0xffffff00 broadcast 10.11.12.255
        netif: <...>
        flowswitch: <...>
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active
        type: Wi-Fi
        agent domain:Skywalk type:NetIf flags:0xa443 desc:"Userspace Networking"
        agent domain:Skywalk type:FlowSwitch flags:0x4403 desc:"Userspace Networking"
        link quality: 100 (good)
        state availability: 0 (true)
        scheduler: FQ_CODEL (driver managed)
        uplink rate: 251.15 Mbps [eff] / 304.20 Mbps
        downlink rate: 251.15 Mbps [eff] / 304.20 Mbps [max]
        qosmarking enabled: yes mode: none
        low power mode: disabled
        multi layer packet logging (mpklog): disabled
```

**Comment by GerardDirks** [comment]
Hello

In my opinion the WiFi Ethernet Speed will be set at the Bootup from the Mac!

In my case in is now 780 Mbps but when I look to the Network Utility the effective speed is only 304.2 MBits/s

Gérard

—————————————————————————————————
Dipl. Ing. Gérard Dirks
Speerstrasse 9
CH-8738 Uetliburg (SG), Switzerland
Tel.: +41-44-515 25 70 Fax.: +41-44-515 25 77, GSM.: +41-79-400 39 09
E-Mail: gerard@dirks.ch
—————————————————————————————————

**Comment by shaizu** [comment]
I've issue with horndis and usb wifi tp-link wn725n
macOS version is 10.15.7 (19H2)
menumeter version is 2.0.8

**Comment by yujitach** [comment]
The bug fix for the max interface speed incorrectly reported is now in the release https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.1 .
I'm going to tentatively close this issue.

Please continue reporting the known issue of no download/upload speed shown in #143.

**Comment by fwenzel** [comment]
This commit, it seems like: https://github.com/yujitach/MenuMeters/commit/ad2ef922b6a5dafec088ca81916bf91f617efee8

Nice solution - I tried to fix this a while ago via API and did not find a way. ifconfig had not occurred to me, but seems like a solid way to do this.
