### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by shtefanilie** [yujitach/MenuMeters#157]
Hey, I really enjoy using this software and been doing so for a couple of years now. May I suggest adding donation methods? I would really buy you the team at least a coffee or pizza. Keep up the good work! 💯

**Comment by yujitach** [comment]
Thanks, but MenuMeters are maintained by a lot of people on GitHub, so I can't receive the donations alone, and there's no way to properly distribute the donations to other contributors. 

If you can, please donate something to charitable causes.
