### ISSUE TITLE
Show CPU Throttling

### ISSUE THREAD

**Issue by dmarkey** [yujitach/MenuMeters#158]
I would be nice if when the CPU is being throttled a warning appears(perhaps the temperature widget?)

Thanks!

David

**Comment by Sacrome** [comment]
To any contributors; You might be able to parse throttling info from the output of `pmset -g thermlog`. 
It outputs the following while running on 100%: 

```
2020-06-26 12:30:37 +0200 CPU Power notify
	CPU_Scheduler_Limit 	= 100
	CPU_Available_CPUs 	= 8
	CPU_Speed_Limit 	= 100
```

And may output this when throttling: 

```
2020-06-26 12:30:37 +0200 CPU Power notify
	CPU_Scheduler_Limit 	= 40
	CPU_Available_CPUs 	= 8
	CPU_Speed_Limit 	= 28
```

**Comment by yujitach** [comment]
It can be programmatically obtained via  `IOPMCopyCPUPowerStatus`, see https://developer.apple.com/documentation/iokit/1557079-iopmcopycpupowerstatus .

https://github.com/beltex/SystemKit should also be helpful.

**Comment by yujitach** [comment]
It is implemented in the latest commit, and will be available in the next release.
