### ISSUE TITLE
CPU thermometer disappears when theme auto-switches

### ISSUE THREAD

**Issue by phototrek** [yujitach/MenuMeters#159]
If you have the theme set to automatic, so that switches from light to dark at sunset, the CPU thermometer just disappears (grey on grey). Once you toggle manually, the outline of the thermometer, and the text, appears.

<img width="357" alt="Screenshot 2020-04-29 20 05 37" src="https://user-images.githubusercontent.com/3420977/80667808-02ad8180-8a55-11ea-8f73-09631e326611.png">
<img width="129" alt="Screenshot 2020-04-29 20 05 48" src="https://user-images.githubusercontent.com/3420977/80667815-050fdb80-8a55-11ea-89ae-3ed84f052729.png">
<img width="706" alt="Screenshot 2020-04-29 20 06 03" src="https://user-images.githubusercontent.com/3420977/80667816-050fdb80-8a55-11ea-95db-1e74da085e7e.png">

**Comment by yujitach** [comment]
Fix should be available via auto-update.

**Comment by yujitach** [comment]
Uh, the release 2.0.6 I uploaded about a day ago didn't actually fix it, due to my stupid last minute change. I made 2.0.6.1 available via auto-update, which should really fix it this time.
