### ISSUE TITLE
Add "Activity Monitor" to network dropdown

### ISSUE THREAD

**Issue by rdp** [yujitach/MenuMeters#161]
Today under the "cpu menu" there is the option to open the "activity monitor" to see which process is using "all of that cpu" (drill down to see details).

For network the drilldown options are "Network Utility" "Network Preferences" and "MenuMeters Preferences".  None of those allow for drilling down to see which process is using the network.

Suggestion/feature request: add option to open "activity monitor" also from the network dropdown, to allow for seeing this.

**Comment by rdp** [comment]
Sorry if I already asked this I didn't see it with a search...

**Comment by yujitach** [comment]
Now in the latest release https://github.com/yujitach/MenuMeters/releases/tag/2.0.8 .

**Comment by rdp** [comment]
Ahh works great, thank you!
