### ISSUE TITLE
Memory menumeter shows wrong swap file path

### ISSUE THREAD

**Issue by CGCastro** [yujitach/MenuMeters#164]
I edited /etc/sysctl.conf , added  "vm.swapfileprefix=/somedirectory/pagefile" to change the path to my swapfile but menumeters does not reflect this change and says 0 swap files present in private/var/vm although the swapfile exists at the "somedirectory" location
notice that the command also changes the name of the swapfile to pagefile

maybe you are assuming that all swapfiles are in the standard place with the standard name, you probably should probe sysctl vm.swapfileprefix to find out what is really happening
running Mac OS High Sierra on an old MacBook Pro going to try the same on an iMac with Catalina

**Comment by yujitach** [comment]
Released as https://github.com/yujitach/MenuMeters/releases/tag/2.0.8 . In fact the default swapfile path changed in Big Sur, so @CGCastro's comment was very prescient!
