### ISSUE TITLE
Feature Request: Static menu bar icon

### ISSUE THREAD

**Issue by dschuessler** [yujitach/MenuMeters#165]
I love the CPU statistics you see when you click on the CPU icon, but I find the animated icon itself distracting.

The ideal solution for me would be an option for a static menu bar icon that is nothing more than a symbol. When you'd click on it, it would show the same menu you see when clicking on the default animated menu bar entries.

**Comment by yujitach** [comment]
It's provided in the latest 2.0.7 available via auto update.
