### ISSUE TITLE
Bug in the CPU meter

### ISSUE THREAD

**Issue by yujitach** [yujitach/MenuMeters#17]
I've got the following message by email:

> On a 12-core Mac Pro, if I turn off “show average for multiple processors as a single display”, the only display option that will display anything is thermometer.  I would like to display graph, but if any of the other options are chosen, nothing is displayed.

**Comment by teras** [comment]
I have also another issue similar to that. On a 4 core hyper-threaded CPU (viewed as 8-core), I can see 8 bars, but the 1-3-5-7 is the same as well as the 2-4-6-8. 
To make it more obvious I attached a screenshot.
It seems like it understands only 2 cores, and for the other just replicates itself.

![screen shot](https://cloud.githubusercontent.com/assets/592568/11020561/69df8ec6-862b-11e5-8ebc-cdbcb76563a1.png)

**Comment by pydolan** [comment]
Any update on this issue?  What's reported in CPU meter does not seem to match Activity Monitor, sorted by CPU.

**Comment by yujitach** [comment]
The CPU meter works OK on my machine, see <img width="220" alt="2016-05-20 20 53 53" src="https://cloud.githubusercontent.com/assets/5449811/15525402/f510db3c-2264-11e6-8f30-e8bbb9f06d03.png"> The four meters show different graphs.

**Comment by resuna** [comment]
I thought I was seeing the same problem as @teras on my "new" quad core mini, but I have fiddles with high-CPU programs and I'm seeing different results. Possibly OS X is doing a better job at balancing the load?

I just wish I could suppress only the hyperthreaded pseudo-cores. Kind of like the "show average" option? Can we consider that a feature request?

**Comment by yujitach** [comment]
This is now a duplicate of #72. (#72 is newer, but it contains more info. So I decided to close this instead.)
