### ISSUE TITLE
[Feature request] All custom bar colors to include transparency (alpha)

### ISSUE THREAD

**Issue by mjbaldwin** [yujitach/MenuMeters#176]
I use two bar meters for overall CPU and memory pressure, and I've set the colors to look great in light mode (red and blue):

![image](https://user-images.githubusercontent.com/160959/94206733-248c2280-fe94-11ea-9b0e-3a2136b75045.png)

But when I switch to dark mode at night, the colors are way too bright. What works really well for colored UX elements to work across both light and dark mode, is instead of being low-saturation, is to be high-saturation but low-opacity.

So the feature request is to use the macOS color picker to use whatever flag is necessary to include the "Opacity" slider, see at bottom:

![image](https://user-images.githubusercontent.com/160959/94206894-7e8ce800-fe94-11ea-937c-83cd348a0b1f.png)

Hope this would be a very simple fix.

Thanks and great work!

**Comment by yujitach** [comment]
Yeah it was really a single line of code. It's shocking that even in the year 2020 macOS still defaults not to show opacity slider in the color panel unless this feature is explicitly enabled. 

It's fixed in the latest release 2.0.9.
