### ISSUE TITLE
to uninstall and remove from Mac

### ISSUE THREAD

**Issue by random105** [yujitach/MenuMeters#178]
I can't seem to uninstall the app for it is always open

**Comment by JackOats48** [comment]
Same here! Can't bin it - because it is open. Can't find it in Library/Preferences pane - it's just not there. This is Catch 22 - very annoying.

**Comment by yujitach** [comment]
You can quit it by first opening the app's preferences, and then doing Cmd-Q (or choosing Quit from the Dock icon.)

Then you can move the app to the trash.

The recent versions of MenuMeters is no longer a preference pane, so it's not found in Library/Preference\ Panes. It's just a standard .app and can be found in any place you have placed it.
