### ISSUE TITLE
Memory usage color bug

### ISSUE THREAD

**Issue by alexclewontin** [yujitach/MenuMeters#179]
I am still getting the bug where black text does not show up in dark mode (or white text does not show up in light mode) for the memory usage element. I can set the text to either black or white using the color picker to make it show up on dark or light theme, but I use the Auto appearance setting in MacOS, which switches from light mode in the day to dark mode at night. I believe this is the same problem that used to show up for CPU usage, but was later fixed.

EDIT: I am using version 2.0.7

EDIT 2: I have it configured to show "Used/Free Totals", and have checked "Show Used/Free Labels", but have "Show paging activity indicator" unchecked

**Comment by yujitach** [comment]
Yeah it's still a problem (and is in fact much worse in Big Sur). Could you attach a screenshot? Otherwise there's no way to fix.

**Comment by alexclewontin** [comment]
Mine is in fact worse than the above, as I'd prefer to keep it black/white.

White on light mode:
<img width="646" alt="Screen Shot 2020-10-12 at 11 41 51 AM" src="https://user-images.githubusercontent.com/28086613/95765653-30dbf200-0c80-11eb-8f64-f958fe571d7e.png">

White on dark mode:
<img width="646" alt="Screen Shot 2020-10-12 at 11 42 04 AM" src="https://user-images.githubusercontent.com/28086613/95765667-35080f80-0c80-11eb-8618-f7629096abf0.png">

Black on light mode:
<img width="646" alt="Screen Shot 2020-10-12 at 11 42 34 AM" src="https://user-images.githubusercontent.com/28086613/95765686-39ccc380-0c80-11eb-8190-c0a9e20bcc9c.png">

Black on dark mode:
<img width="646" alt="Screen Shot 2020-10-12 at 11 42 49 AM" src="https://user-images.githubusercontent.com/28086613/95765707-3f2a0e00-0c80-11eb-861a-a7fd4dd52333.png">

The white is pure white (255, 255, 255) and the black is pure black (0, 0, 0). Interestingly, it disappears even when the background is *not* pure white/pure black, which I would speculate means the OS is assuming something about the transparency.

**Comment by yujitach** [comment]
I'd like to know your opinion for the latest release, available either from the Auto Update or from https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.1 .
