### ISSUE TITLE
OS X 10.11.1 claims prefPane is damaged

### ISSUE THREAD

**Issue by Toweri** [yujitach/MenuMeters#18]
The resulting prefPane cannot be installed on OS X 10.11.1
Double-clicking the prefPane will result in error:
"'MenuMeters.prefPane' is damaged and can't be opened. You should move it to the Trash."

I have re-downloaded the zip archive and retried, to no avail.
Please verify compatibility with OS X 10.11.1 and advise.

**Comment by coolboiime** [comment]
Change the setting to "Allow apps downloaded from anywhere" inside System Preferences > Security & Privacy. Once you launch the prefPane, change the setting back.

**Comment by yujitach** [comment]
Hmm, in my testing it opened OK without setting to "Allow apps downloaded from anywhere" on 10.11.0 and 10.11.1 ...

**Comment by coolboiime** [comment]
I assumed it was this issue. I didn't need to change the setting either.

**Comment by Toweri** [comment]
"Allow apps downloaded from:" was the thing, after all.
I had this setting as "Mac App Store and identified developers"
Changing it to "Anywhere" solved the problem.
The most daily useful Mac utility is back! Thank you Yuji Tachikawa for porting it to OS X 10.11.
