### ISSUE TITLE
"Opens specific panes" mis-selects tab

### ISSUE THREAD

**Issue by mLewisLogic** [yujitach/MenuMeters#182]
Selecting "Open Activity Monitor" from:
* CPU: works as expected
* Disk: opens/selects Energy
* Memory: opens/selects GPU
* Network: opens/selects disk

For ref, in Activity Monitor my available tabs are: [CPU, GPU, Memory, Energy, Disk, Network]

version: 2.0.8

**Comment by yujitach** [comment]
Thanks, I didn't know that some Mac's have a GPU tab in the Activity Monitor. 

I tried to fix it in the new release 2.0.8.1 available at https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.1 . Could you download it and test it?

**Comment by mLewisLogic** [comment]
Cool! Confirmed that the new release fixes the tab selection issue.
Thanks!

**Comment by yujitach** [comment]
Thank you for checking it. 2.0.8.1 is now made public.
