### ISSUE TITLE
CPU Percentage unreadable with dark menu bar

### ISSUE THREAD

**Issue by toobuntu** [yujitach/MenuMeters#183]
The CPU Percentage is black text and the color is not configurable. Black text does not show up on a dark menu bar for the CPU Percentage usage element. (See the far right of the attached screenshot.)

MenuMeters 2.0.8
macOS 10.13.6
![menumeters-screenshot-201028](https://user-images.githubusercontent.com/674390/97500820-aa453700-1946-11eb-9887-cc73cc6e440d.jpg)

**Comment by yujitach** [comment]
I tried to fix it in the new release 2.0.8.1: https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.1 

Could you download it and test it? As I have no pre-Mojave Mac, I can't test it myself.

**Comment by toobuntu** [comment]
Looking good. Thank you for the quick fix.

MenuMeters 2.0.8.1
macOS 10.13.6
![menumeters-screenshot-201029](https://user-images.githubusercontent.com/674390/97593860-787cb080-19d8-11eb-963a-81607357eba5.jpg)

**Comment by yujitach** [comment]
Thank you for checking it. 2.0.8.1 is now made public.
