### ISSUE TITLE
[Workaround Request] Add checkbox option to use netstat for when "No download speed shown #143" occurs with third party NICs

### ISSUE THREAD

**Issue by hoondi** [yujitach/MenuMeters#184]
As Apple's IONetwork library doesn't seem to show download values anymore for 3rd party NICs, netstat still reports download rates.

This can be confirmed by running:
`netstat -i 1 1`
There are two columns labelled "bytes" for input and output.
and to get the 6th column:
`netstat -i 1 1 | awk '{print $6}'`

Is it possible to add code for an option to use netstat for upload and download?

Cheers,

**Comment by yujitach** [comment]
Thanks,  the code for `netstat` is thankfully available at [this URL at Apple's opensource repository](https://opensource.apple.com/source/network_cmds/network_cmds-596.100.2/netstat.tproj/), so there might be a way to incorporate it directly. 

The solution for #155 too was also using `ifconfig` instead of IOKit, and the source code for `ifconfig` was available as well, but unfortunately it used a lot of non-public header files. Let's see how it fares this time.

**Comment by hoondi** [comment]
I'm using this for the time being:

```
#!/bin/sh

INTF=(`route -n get default | grep -o "interface: .*" | sed -e 's/interface: //'`)

# get the current number of bytes in and bytes out
sample1=(`/usr/sbin/netstat -ib | awk "/$INTF/"'{print $7" "$10; exit}'`)

# wait one second
sleep 1

# get the number of bytes in and out one second later
sample2=(`/usr/sbin/netstat -ib | awk "/$INTF/"'{print $7" "$10; exit}'`)

# find the difference between bytes in and out during that one second
# and convert bytes to kilobytes
results=(`echo "2k ${sample2[0]} ${sample1[0]} - 1024 / p" \
		  "${sample2[1]} ${sample1[1]} - 1024 / p" | dc`)

# print the results
printf "in: %.2f Kb/sec\nout: %.2f Kb/sec\n" ${results[0]} ${results[1]}
```
Don't know if it's helpful for you or others in the meantime…

**Comment by hoondi** [comment]
Actually, I think netstat is also broken… 

my gateway is en10 and so if I run the following in terminal:
`netstat -w1 -I"en10";`
and then run a speedtest.net, I don't see the input bytes column change at all… 8((

` % netstat -w1 -I"en10";
            input         (en10)           output
   packets  errs      bytes    packets  errs      bytes colls
         0     0          0         10     0        980     0
         0     0          0         13     0       1241     0
         0     0          0         19     0       2723     0
         0     0          0          8     0        848     0
         0     0          0          8     0        848     0
         0     0          0          9     0       1012     0
         0     0          0         11     0       1319     0
         0     0          0         20     0       2401     0
         0     0          0         15     0       1634     0
         0     0          0          5     0        643     0
         0     0          0         12     0       1361     0
         0     0          0         16     0       3235     0
         0     0          0         21     0       3050     0
         0     0          0          8     0        848     0
         0     0          0         12     0       1173     0
         0     0          0          9     0        914     0
         0     0          0          8     0        848     0
         0     0          0         21     0       3048     0
         0     0          0         12     0       1218     0
         0     0          0          9     0        994     0
            input         (en10)           output
   packets  errs      bytes    packets  errs      bytes colls
         0     0          0          8     0        848     0
         0     0          0          9     0        971     0
         0     0          0          8     0        848     0
         0     0          0         19     0       2377     0
         0     0          0         47     0       7480     0
         0     0          0         17     0       3500     0
         0     0          0         46     0       5017     0
         0     0          0         29     0       3774     0
         0     0          0        447     0      39826     0
         0     0          0       2652     0     180058     0
         0     0          0       1309     0      87125     0
         0     0          0       2249     0     148816     0
         0     0          0       2276     0     150487     0
         0     0          0       2380     0     158942     0
         0     0          0       4264     0     291460     0
         0     0          0       2405     0     159571     0
         0     0          0       3170     0     212156     0
         0     0          0       2747     0     183014     0
         0     0          0       3235     0     218373     0
         0     0          0       3393     0     232431     0
         0     0          0       2700     0     181472     0
            input         (en10)           output
   packets  errs      bytes    packets  errs      bytes colls
         0     0          0       2702     0     181097     0
         0     0          0       3206     0     215353     0
         0     0          0       3837     0     258167     0
         0     0          0          3     0        469     0
         0     0          0       1231     0    3222048     0
         0     0          0       1232     0    2281113     0
         0     0          0        783     0    2900214     0
         0     0          0        797     0    2870567     0
         0     0          0        808     0    2906472     0
         0     0          0        742     0    2658588     0
         0     0          0        791     0    2870435     0
         0     0          0        808     0    2820776     0
         0     0          0        829     0    2855466     0
         0     0          0        795     0    2909026     0
         0     0          0        837     0    2974332     0
         0     0          0        251     0     732926     0
         0     0          0         14     0       1693     0
         0     0          0        310     0      32836     0
^C
`

Anyone else with a 3rd party NIC able to confirm the above?

**Comment by yujitach** [comment]
Hi @hoondi , could you test https://github.com/exelban/stats and tell me if it shows the correct speed? If so, I can incorporate stats' code to MenuMeters.

**Comment by yujitach** [comment]
temporarily closing this issue; let's discuss it further in the original #143 .
