### ISSUE TITLE
[Bug] Incompatible with auto hide/show menu bar option

### ISSUE THREAD

**Issue by EddyLB** [yujitach/MenuMeters#189]
When the "Automatically hide and show the menu bar" option in System Preferences / Dock & Menu Bar is enabled (macOS Big Sur), MenuMeters 2.0.8.1 does not display meters. And after disabling this option, one has to restart MenuMeters to get it working as expected.

**Comment by yujitach** [comment]
Released an update https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.2 which should hopefully fix the issue. I close this thread; if the problem persists, please report in #185 .
