### ISSUE TITLE
Display of throughput only seems to work correctly when left clicked.

### ISSUE THREAD

**Issue by eay** [yujitach/MenuMeters#192]
I have 2 network interfaces active, thunderbolt and wifi.  When I left click and open the network panel, the values
reflect the primary interface.  When I close the popup, the network displays 0/0 with occasional flashes of a
number.  This is under MacOS 11 (just installed).  I believe this is a MacOS 11 issue.

**Comment by EddyLB** [comment]
I observe a similar issue while there is only one interface currently active. I attach a video showing that the throughput changes from zero with occasional flashes of a low number (B/s) to a more realistic value (MB/s) when I display the panel.

[Screen Recording 2020-11-15 at 20.12.45.mov.zip](https://github.com/yujitach/MenuMeters/files/5542945/Screen.Recording.2020-11-15.at.20.12.45.mov.zip)

**Comment by Mathek** [comment]
I have the same issue and a similar setup (like EddyLB).

Reagrds

**Comment by yujitach** [comment]
Thanks for the reports. Is this bug new to Big Sur? Did it work OK on Catalina?

**Comment by Mathek** [comment]
I did installed of BigSur. So there are no old MenuMeter files involved.
Today it is working like it should. I don‘t know what solved the issue for now. It maybe a couple of restarts. 

I‘am going to report if it comes back.

**Comment by csimarro2** [comment]
Same behaviour here. I have the feeling it started happening when I updated to 2.0.9. I am in Big Sur. How can I completely wipe the MenuMeters user preferences to start it from scratch?

**Comment by yujitach** [comment]
@csimarro2 Please don't wipe the preference. Could you try downloading old version (2.0.8.3 or 2.0.7) from https://github.com/yujitach/MenuMeters/releases and see the problem persists? That would help me greatly to track down what is the source of the problem.

**Comment by csimarro2** [comment]
@yujitach you are right! it works fine for 2.0.7 (it does not for 2.0.8 onwards)

**Comment by yujitach** [comment]
Thanks. Has anybody have problems with 2.0.9 on Catalina and before?

**Comment by yujitach** [comment]
Could you test if the attached version 2.0.9.1 works?
[MenuMeters_2.0.9.1.zip](https://github.com/yujitach/MenuMeters/files/5547448/MenuMeters_2.0.9.1.zip)

I just reverted the drawing method to 2.0.7. But if it works, I consider it the bug on the part of implementations of `NSStatusItem`s on Big Sur, not my code... due to various reasons.

**Comment by joethefox** [comment]
Hello, 

I have the exact same opening issue under MacOS Big Sur and version 2.0.9.1 did not solved the issue :(
In my case, as soon as you switch to another desktop it start working again. At some point, during the day, it stops working and switching desktop do the trick to fix it again.

**Comment by csimarro2** [comment]
Version 2.0.9.1 works well for me with Big Sur

**Comment by eay** [comment]
It worked fine on Catalina

**Comment by yujitach** [comment]
Thanks everyone for the reports. It seems that it's really an issue with Big Sur's implementation of menu bar items. Or more precisely, there are multiple issues, since 2.0.9.1 solved the issue for @csimarro2 but not for @joethefox , and even for @joethefox it depends on the desktop picture...

@joethefox , does the issue appear both for the light menubar and for the dark menubar? (Note that on Big Sur, whether the menubar is dark or light is not determined by the global dark/light setting, but rather by the desktop picture.) 

I got an email from a user saying that a similar issue manifested only on the dark menubar...

**Comment by joethefox** [comment]
Yes, looks like it's kind of related to the desktop background light/dark/dynamic. I tried to figure out when it happens but looks like it's random when trying to change configuration with both desktops. It can happen when both desktop 1 and 2 are configured in dynamic mode, light mode or dark mode or any combination of them.

**Comment by yujitach** [comment]
I've received a report via email saying that "System preferences->Accessibility->Display->Reduce transparency" helped. Could someone confirm?

Also, I'd like to reproduce the problem on my Mac too. Could someone share the desktop picture with me (and the dark/light mode setting) where this issue happens?

**Comment by abegel** [comment]
@yujitach Your 2.0.9.1 did not fix the problem for me on MacOS Big Sur.

**Comment by fvalle1** [comment]
@yujitach I am experiencing this issue too. I am on BigSur 11.0.1 (20B29) and using MM 20.9

**Comment by esetleges** [comment]
Mac OS BigSur (upgraded)

v2.0.9.1 - did not fix the problem
Reset Menumeter pref file - did not fix the problem
"System preferences->Accessibility->Display->Reduce transparency" - did not fix the problem

Problem (flashing) appears only in DARK Mode(!). Light Mode is correct (v.2.0.9.1) - Hope this info helps to locate the issue.

**Comment by Mathek** [comment]
Today I plugged in an Ethernet cable and noticed that the issues is back again.
(A couple of days before it disappeared by it self on Wifi connection stats)
So maybe the switch of the main network connection could be a cause?

I'm running BigSur 11.0.1 on MBP 15" 2018

**Comment by sSalvaXx** [comment]
Just installed 2.0.9 but the problem persists (Big Sur) --throughput is 0/0 unless I click on it

**Comment by pfahlstrom** [comment]
I have this problem too. If I clear the checkbox that says "ignore values below 1 K/s" then it often shows values of a few bytes per second. So it seems like it's getting values from somewhere—like another one of the interfaces that isn't actually being used—instead of the primary interface.

**Comment by yujitach** [comment]
I made a special debug build which shows the NetMeter also within a separate window, as the attached image shows:
![shot](https://user-images.githubusercontent.com/5449811/100194941-e960ab00-2f39-11eb-8851-4e7e25fe88d7.png)

This should tell us whether the bug is on Big Sur's side or on MenuMeters' side.

If you're affected by the issue discussed here, could you download and try it?

**Comment by fvalle1** [comment]
Hello @yujitach , I downloaded the special build and the values in the window are coherent with the ones in the bar. Both are not correct. I am on BigSur 11.0.1 (20B29). I am here if you need further investigation.

**Comment by Mathek** [comment]
@yujitach 
I tested v2.1.1 with switching between [Wifi](https://drive.google.com/file/d/1VwyXjjOSZkMk6lQdnYAqggAIZZ5ZTeNM/view?usp=sharing) and [Ethernet](https://drive.google.com/file/d/1KDEGTSlC_AAJkQSB2_mpNCiTCLp2jH2l/view?usp=sharing) connection.
(I restarted MacOs after installing v2.1.1)

As for now there is no problem with the stats. The screenshots are linked.

**Comment by sSalvaXx** [comment]
I just installed the debug release (2.1.1) after uninstalling the previous release. Problem is still there (in both menu bar and app window). Both always show 0/0 unless right-clicked on the menu bar.

**Comment by csimarro2** [comment]
@yujitach as I said 2.0.9.1 and 2.1.0 solved the issue for me. However I am still receiving notifications about this issue so I wanted to test a bit further. Now if I switch to Light mode, the issue 0/0 is back. When I switch back to Dark it disappears and works fine...

**Comment by yujitach** [comment]
@csimarro2 Could you download and test the debug build I attached above? Does it show the problem only for the Dark mode in your case?

**Comment by csimarro2** [comment]
In Light mode both the bar and the window show 0/0. Both work well in Dark mode. 
![Screenshot 2020-11-25 at 10 18 11](https://user-images.githubusercontent.com/55150624/100214339-adaced80-2f07-11eb-9550-a560fc3e8193.png)

**Comment by yujitach** [comment]
Thanks everyone for the reports. Then the issue might be that the timer to update the info might not be firing at all.

Could everyone test the version here: 
[MenuMeters-2.1.1.issue192.a.zip](https://github.com/yujitach/MenuMeters/files/5596899/MenuMeters-2.1.1.issue192.a.zip)

It adds a counter in front of the tx/rx values to show when the net meter is updated. If the counter is increased and the rate is zero, then what's broken is the part reading the rate. If the counter is not increasing, then what's broken is the part to periodically update the image.

**Comment by fvalle1** [comment]
In my case now the speed is correctly shown in both the bar and in the debug window.
The counter updates itself too

**Comment by sSalvaXx** [comment]
MenuMeters-2.1.1.issue192.a.zip fixed the issue for me

**Comment by joethefox** [comment]
Sadly still the same issue here with MenuMeters-2.1.1.issue192.a.zip.

Here is a short screen recording https://drive.google.com/file/d/1utOka1n7dAoQLKrx_ylHY5XQjrskLhFg/view?usp=sharing

**Comment by yujitach** [comment]
@sSalvaXx That's strange, because I didn't put any fix... I just put a debug aid...
@joethefox That's reasonable, because I didn't put any fix... I just put a debug aid...

Joking aside, I'd like to ask @joethefox a question. Does it work correctly if you click the net menumeter and bring up the menu? 

@joethefox's video is helpful too. The counter should increase one by one, but it only increases by 3 in the video. I wonder why.

**Comment by sSalvaXx** [comment]
I noticed after writing my comment that the changing numbers in the menu bar are not the throughput but some kind of random numbers. Therefore, I confirm that the issue is not fixed

**Comment by joethefox** [comment]
nope, if I click the net menumeter and bring up the menu it is still
broken, otherwise if I click the net menumeter and leave it focused then it
works. To remark, when focused the counter, even if not completely visible,
seems increased by 1.

Video:
https://drive.google.com/file/d/1mY0HjCBn5DgyCBcdNTePK7mAHyY9qCmD/view?usp=sharing

**Comment by Pr0xS** [comment]
I have been doing some testing and It seem that the bug is related with the time, for me it only fails from 9:00 to 15:00 more or less. And it doesn't seem to take into account if you are using dynamic backgrounds or simple images.
Also this could be the reason why some people are reporting that the problem is fixed even where there was no fix on the patch.
I can replicate the bug 100% of the time changing the time manually

**Comment by fvalle1** [comment]
I tried the test suggested by @Pr0xS and the same happens to me. If the time is set around 12:00 it doesn't work, anyway it works..

**Comment by yujitach** [comment]
OK, now that the problem seems to be in the timer, could you test the following version: 
[MenuMeters-2.1.1.issue192.b.zip](https://github.com/yujitach/MenuMeters/files/5599865/MenuMeters-2.1.1.issue192.b.zip)

As shown below, please click the button to copy the info when the netmeter is not working correctly, and report on this issue page.

<img width="592" alt="スクリーンショット 2020-11-26 10 01 56" src="https://user-images.githubusercontent.com/5449811/100296039-8d943180-2fce-11eb-9f34-a3bce726eb29.png">

**Comment by sSalvaXx** [comment]
105 # 2020-11-26 03:01:59 +0000 # 2.343695998191833
104 # 2020-11-26 03:01:56 +0000 # 0.001402020454406738
103 # 2020-11-26 03:01:56 +0000 # 0.002284049987792969
102 # 2020-11-26 03:01:56 +0000 # 2.070863962173462
101 # 2020-11-26 03:01:54 +0000 # 0.001482009887695312
100 # 2020-11-26 03:01:54 +0000 # 0.002339959144592285
99 # 2020-11-26 03:01:54 +0000 # 2.396077036857605
98 # 2020-11-26 03:01:52 +0000 # 0.001433968544006348
97 # 2020-11-26 03:01:52 +0000 # 0.006385087966918945
96 # 2020-11-26 03:01:52 +0000 # 2.203380107879639
95 # 2020-11-26 03:01:50 +0000 # 0.001423001289367676
94 # 2020-11-26 03:01:50 +0000 # 0.002115011215209961
93 # 2020-11-26 03:01:50 +0000 # 2.130263924598694
92 # 2020-11-26 03:01:47 +0000 # 0.001277923583984375
91 # 2020-11-26 03:01:47 +0000 # 0.002086043357849121
90 # 2020-11-26 03:01:47 +0000 # 2.08747398853302
89 # 2020-11-26 03:01:45 +0000 # 0.001696109771728516
88 # 2020-11-26 03:01:45 +0000 # 0.002723097801208496
87 # 2020-11-26 03:01:45 +0000 # 2.220044016838074
86 # 2020-11-26 03:01:43 +0000 # 0.001860976219177246
85 # 2020-11-26 03:01:43 +0000 # 0.005355954170227051
84 # 2020-11-26 03:01:43 +0000 # 2.015286087989807
83 # 2020-11-26 03:01:41 +0000 # 0.001433014869689941
82 # 2020-11-26 03:01:41 +0000 # 0.002418041229248047
81 # 2020-11-26 03:01:41 +0000 # 2.093924999237061
80 # 2020-11-26 03:01:39 +0000 # 0.001933097839355469
79 # 2020-11-26 03:01:39 +0000 # 0.007941007614135742
78 # 2020-11-26 03:01:39 +0000 # 2.219707012176514
77 # 2020-11-26 03:01:37 +0000 # 0.00214695930480957
76 # 2020-11-26 03:01:37 +0000 # 0.01159405708312988
75 # 2020-11-26 03:01:37 +0000 # 2.034693002700806
74 # 2020-11-26 03:01:35 +0000 # 0.001779079437255859
73 # 2020-11-26 03:01:35 +0000 # 0.00299990177154541
72 # 2020-11-26 03:01:35 +0000 # 2.244953036308289
71 # 2020-11-26 03:01:33 +0000 # 0.002660036087036133
70 # 2020-11-26 03:01:33 +0000 # 0.00368201732635498
69 # 2020-11-26 03:01:33 +0000 # 2.024794936180115
68 # 2020-11-26 03:01:30 +0000 # 0.001379966735839844
67 # 2020-11-26 03:01:30 +0000 # 0.002318978309631348
66 # 2020-11-26 03:01:30 +0000 # 1.999675035476685
65 # 2020-11-26 03:01:28 +0000 # 0.001253962516784668
64 # 2020-11-26 03:01:28 +0000 # 0.002138018608093262
63 # 2020-11-26 03:01:28 +0000 # 1.999618053436279
62 # 2020-11-26 03:01:26 +0000 # 0.001244902610778809
61 # 2020-11-26 03:01:26 +0000 # 0.003075003623962402
60 # 2020-11-26 03:01:26 +0000 # 2.214675903320312
59 # 2020-11-26 03:01:24 +0000 # 0.00150597095489502
58 # 2020-11-26 03:01:24 +0000 # 0.003840923309326172
57 # 2020-11-26 03:01:24 +0000 # 2.023787021636963
56 # 2020-11-26 03:01:22 +0000 # 0.001599907875061035
55 # 2020-11-26 03:01:22 +0000 # 0.003828048706054688
54 # 2020-11-26 03:01:22 +0000 # 2.229575037956238
53 # 2020-11-26 03:01:20 +0000 # 0.001742005348205566
52 # 2020-11-26 03:01:20 +0000 # 0.003412008285522461
51 # 2020-11-26 03:01:20 +0000 # 2.209331035614014
50 # 2020-11-26 03:01:18 +0000 # 0.00129401683807373
49 # 2020-11-26 03:01:18 +0000 # 0.008798003196716309
48 # 2020-11-26 03:01:18 +0000 # 2.01883602142334
47 # 2020-11-26 03:01:16 +0000 # 0.001417994499206543
46 # 2020-11-26 03:01:16 +0000 # 0.008445978164672852
45 # 2020-11-26 03:01:16 +0000 # 2.21035099029541
44 # 2020-11-26 03:01:14 +0000 # 0.001616001129150391
43 # 2020-11-26 03:01:14 +0000 # 0.00415503978729248
42 # 2020-11-26 03:01:14 +0000 # 2.211156964302063
41 # 2020-11-26 03:01:11 +0000 # 0.001320004463195801
40 # 2020-11-26 03:01:11 +0000 # 0.008255958557128906
39 # 2020-11-26 03:01:11 +0000 # 2.206972002983093
38 # 2020-11-26 03:01:09 +0000 # 0.001346945762634277
37 # 2020-11-26 03:01:09 +0000 # 0.009322047233581543
36 # 2020-11-26 03:01:09 +0000 # 2.038994073867798
35 # 2020-11-26 03:01:07 +0000 # 0.001409053802490234
34 # 2020-11-26 03:01:07 +0000 # 0.003483891487121582
33 # 2020-11-26 03:01:07 +0000 # 2.031270027160645
32 # 2020-11-26 03:01:05 +0000 # 0.002022027969360352
31 # 2020-11-26 03:01:05 +0000 # 0.002831935882568359
30 # 2020-11-26 03:01:05 +0000 # 2.010754942893982
29 # 2020-11-26 03:01:03 +0000 # 0.001495957374572754
28 # 2020-11-26 03:01:03 +0000 # 0.03029000759124756
27 # 2020-11-26 03:01:03 +0000 # 2.217661023139954
26 # 2020-11-26 03:01:01 +0000 # 0.001122951507568359
25 # 2020-11-26 03:01:01 +0000 # 0.006120920181274414
24 # 2020-11-26 03:01:01 +0000 # 2.08733606338501
23 # 2020-11-26 03:00:59 +0000 # 0.001175999641418457
22 # 2020-11-26 03:00:59 +0000 # 0.2054189443588257
21 # 2020-11-26 03:00:58 +0000 # 2.169602036476135
20 # 2020-11-26 03:00:56 +0000 # 0.001110076904296875
19 # 2020-11-26 03:00:56 +0000 # 0.003007054328918457
18 # 2020-11-26 03:00:56 +0000 # 2.054826021194458
17 # 2020-11-26 03:00:54 +0000 # 0.001139998435974121
16 # 2020-11-26 03:00:54 +0000 # 0.01413810253143311
15 # 2020-11-26 03:00:54 +0000 # 2.069050908088684
14 # 2020-11-26 03:00:52 +0000 # 0.001321911811828613
13 # 2020-11-26 03:00:52 +0000 # 0.4890240430831909
12 # 2020-11-26 03:00:52 +0000 # 1.901884913444519
11 # 2020-11-26 03:00:50 +0000 # 1.999914050102234
10 # 2020-11-26 03:00:48 +0000 # 1.889644026756287
9 # 2020-11-26 03:00:46 +0000 # 2.239781022071838
8 # 2020-11-26 03:00:44 +0000 # 0.001527905464172363
7 # 2020-11-26 03:00:44 +0000 # 0.007269978523254395
6 # 2020-11-26 03:00:44 +0000 # 2.086840033531189
5 # 2020-11-26 03:00:42 +0000 # 0.001175999641418457
4 # 2020-11-26 03:00:42 +0000 # 0.0703730583190918
3 # 2020-11-26 03:00:41 +0000 # 0.001212000846862793
2 # 2020-11-26 03:00:41 +0000 # 0.2181360721588135
1 # 2020-11-26 03:00:41 +0000 # 2
netInterval:2

**Comment by yujitach** [comment]
@sSalvaXx Thanks, the timer timing looks clearly wrong. I made a slightly different debug build. Could you test if it runs correctly or not? 
[MenuMeters-2.1.1.issue192.c.zip](https://github.com/yujitach/MenuMeters/files/5600250/MenuMeters-2.1.1.issue192.c.zip)

If it runs correctly, could you further check if the previous debug build shows the problem?

**Comment by sSalvaXx** [comment]
it seems running correctly now !

Please note I have to leave and won't be at my computer for the coming 6 hours. I'll be able to help again when I come back if needed

26 # 2020-11-26 03:30:05 +0000 # 2.404320001602173
25 # 2020-11-26 03:30:03 +0000 # 2.233287930488586
24 # 2020-11-26 03:30:00 +0000 # 2.398200988769531
23 # 2020-11-26 03:29:58 +0000 # 2.011155962944031
22 # 2020-11-26 03:29:56 +0000 # 2.023913025856018
21 # 2020-11-26 03:29:54 +0000 # 2.146481990814209
20 # 2020-11-26 03:29:52 +0000 # 2.052526950836182
19 # 2020-11-26 03:29:50 +0000 # 2.399924039840698
18 # 2020-11-26 03:29:47 +0000 # 2.227213978767395
17 # 2020-11-26 03:29:45 +0000 # 2.214323043823242
16 # 2020-11-26 03:29:43 +0000 # 2.215248942375183
15 # 2020-11-26 03:29:41 +0000 # 2.218103885650635
14 # 2020-11-26 03:29:38 +0000 # 2.221356987953186
13 # 2020-11-26 03:29:36 +0000 # 2.217005968093872
12 # 2020-11-26 03:29:34 +0000 # 2.024735927581787
11 # 2020-11-26 03:29:32 +0000 # 2.026719093322754
10 # 2020-11-26 03:29:30 +0000 # 2.083877086639404
9 # 2020-11-26 03:29:28 +0000 # 2.232533931732178
8 # 2020-11-26 03:29:26 +0000 # 3.322896003723145
7 # 2020-11-26 03:29:22 +0000 # 2.387311935424805
6 # 2020-11-26 03:29:20 +0000 # 2.230635046958923
5 # 2020-11-26 03:29:18 +0000 # 2.004012942314148
4 # 2020-11-26 03:29:16 +0000 # 2.051210999488831
3 # 2020-11-26 03:29:14 +0000 # 2.469521045684814
2 # 2020-11-26 03:29:11 +0000 # 2.211413025856018
1 # 2020-11-26 03:29:09 +0000 # 2
netInterval:2

**Comment by yujitach** [comment]
@sSalvaXx  Thank you very much for your help. I think I finally understood the Big Sur behavior behind the bug.

**Comment by fvalle1** [comment]
That's mine, but it seems to work properly now.

17 # 2020-11-26 08:11:19 +0000 # 2.037276983261108
16 # 2020-11-26 08:11:17 +0000 # 2.310169100761414
15 # 2020-11-26 08:11:15 +0000 # 2.024284958839417
14 # 2020-11-26 08:11:13 +0000 # 2.066612005233765
13 # 2020-11-26 08:11:11 +0000 # 2.119391918182373
12 # 2020-11-26 08:11:09 +0000 # 2.389364957809448
11 # 2020-11-26 08:11:06 +0000 # 2.282145977020264
10 # 2020-11-26 08:11:04 +0000 # 2.407746911048889
9 # 2020-11-26 08:11:01 +0000 # 2.406957030296326
8 # 2020-11-26 08:10:59 +0000 # 2.4046950340271
7 # 2020-11-26 08:10:57 +0000 # 2.036567091941833
6 # 2020-11-26 08:10:55 +0000 # 2.212822914123535
5 # 2020-11-26 08:10:52 +0000 # 2.033231019973755
4 # 2020-11-26 08:10:50 +0000 # 2.334773898124695
3 # 2020-11-26 08:10:48 +0000 # 2.200505018234253
2 # 2020-11-26 08:10:46 +0000 # 2.110188007354736
1 # 2020-11-26 08:10:44 +0000 # 2
netInterval:2

**Comment by yujitach** [comment]
@fvalle1 Thanks. I guess we finally managed to fix this pesky issue...

For those who'd like to know the cause, what was happening was that Big Sur sometimes tell apps repeatedly that the menu bar appearance has changed from light to light, or from dark to dark, when in fact the appearance hasn't changed. In Catalina and before, this never happened: the OS only told the apps that the appearance changed from light to dark or from dark to light.

MenuMeters redraws itself whenever it got this notification. MenuMeters also redraws itself whenever a set interval has passed (default 2 seconds). Now, the transfer rate was computed by dividing the transfer bytes between two redraws by the seconds elapsed. 

The problem with Big Sur was that when two appearance-change notifications came with very little time difference, the transfer bytes between the two are basically zero, showing zero in the menu bar.

The bug is resolved (hopefully) by making MenuMeters redraw only when the set interval has passed. This is enough, because the appearance change is reflected on the menu bar in 2 seconds anyway...

**Comment by Mathek** [comment]
@yujitach 
Thank you! Your support was awesome. 👏

**Comment by csimarro2** [comment]
@yujitach I can also confirm that version MenuMeters-2.1.1.issue192.b works fine for me in both Dark and Light mode. Thanks!

**Comment by joethefox** [comment]
kudos for having tamed the beast! :)

**Comment by sSalvaXx** [comment]
Thank you so much !
Will you release a production version soon (without the debug digits on the menu bar) ?

**Comment by yujitach** [comment]
I made the (pre)release where the bug is hopefully fixed. Could you try
      https://github.com/yujitach/MenuMeters/releases/tag/2.1.1  ?

If no serious problem is reported, I will release it to the auto-update.

**Comment by sSalvaXx** [comment]
> I made the (pre)release where the bug is hopefully fixed. Could you try
> https://github.com/yujitach/MenuMeters/releases/tag/2.1.1 ?
> 
> If no serious problem is reported, I will release it to the auto-update.

all fine on my end with this new pre-release. Many thanks for your support

**Comment by fvalle1** [comment]
all fine with the pre-release for me too

thank you!

**Comment by pfahlstrom** [comment]
Thanks for this rapid fix!!

**Comment by yujitach** [comment]
All righty, I'll release it. I'd like to thank everybody here again for the immense help in fixing this bug, which was very nasty but at the same time challenging in a good way :)
