### ISSUE TITLE
Reported temperature for CPU on mid 2015 macbook is incorrect.

### ISSUE THREAD

**Issue by Impakt** [yujitach/MenuMeters#193]
I keep an eye on CPU temps and noticed that menu meters compared to running `sudo powermetrics --samplers smc |grep -i "CPU die temperature"` is different..

the command can show a temperature of 90 degrees + when throttling but menu meters still shows only 65

**Comment by yujitach** [comment]
I confirm this discrepancy on my machine too. 

Honestly speaking I haven't checked that the [code here](https://github.com/yujitach/MenuMeters/blob/8c668d0230dcf34af4132cd78264cb646fd7d4b2/MenuExtras/MenuMeterCPU/MenuMeterCPUStats.m#L350) contributed by @ololoken to read the temperature off the smc, correctly converts the raw value returned by smc to Celcius. I need to find a correct documentation.

I hope @ololoken notices this discussion and suggest a way forward...

**Comment by ololoken** [comment]
Temperature shown in menumeters is received from proximity sensor (TC0P).
Check here what the "CPU die temperature" is https://discussions.apple.com/thread/6666066

**Comment by yujitach** [comment]
@ololoken Thanks. Where can we get the list of sensors and the smc codes?

**Comment by ololoken** [comment]
[Known SMC Keys](https://app.assembla.com/wiki/show/fakesmc)

**Comment by yujitach** [comment]
Wow, thanks, that's amazing. Who reverse engineered that?

**Comment by Impakt** [comment]
so change `TC0P` to `TC0D` [here](https://github.com/yujitach/MenuMeters/blob/8c668d0230dcf34af4132cd78264cb646fd7d4b2/MenuExtras/MenuMeterCPU/MenuMeterCPUStats.m#L356)?

**Comment by yujitach** [comment]
If you want the die temperature, yes. I'm not sure if changing from the proximity sensor to the die sensor is the right thing, though, since we never said what exactly is meant by the CPU temperature!

**Comment by Impakt** [comment]
the llink @ololoken posted to the apple site has an answer that says you're currently reading a sensor on the heatsink?

**Comment by Impakt** [comment]
I downloaded xcode and cloned the project to see if changing the code would work. Unfortunately it doesn't.

**Comment by Impakt** [comment]
this SMC reader seems to get the CPU die temps ok

https://github.com/hacker1024/coretemp

**Comment by yujitach** [comment]
I think I would just declare that what CPU temperature means in MenuMeters is the temperature from the proximity sensor, not the die temperature.  If we make the change unannounced, many people suddenly think that the temperature of the CPU somehow went up, which is not the case.

The proper solution is to add an option in the preferences to choose exactly which temperature you'd like to show.

**Comment by rozhl** [comment]
My iMac has a "CPU Cores" sensor that is used in the system fan speed settings AFAIK. That would be the best sensor to show in my case... _just adding my 2 cents._

**Comment by yujitach** [comment]
In the latest release you can choose which sensor to display: https://github.com/yujitach/MenuMeters/releases/tag/2.1.4 Please have a look and try.

**Comment by Impakt** [comment]
Hi @yujitach I grabbed the latest version and am using `TC0F` , which seems to do the trick! Strange that there's no `TC0D` option, maybe using Big Sur beta has something to do with it.
