### ISSUE TITLE
Big Sur and blurs the transmit text for some reason

### ISSUE THREAD

**Issue by brewsterkahle** [yujitach/MenuMeters#196]
<img width="260" alt="Screen Shot 2020-11-17 at 7 03 32 PM" src="https://user-images.githubusercontent.com/2703321/99477615-b5690280-2907-11eb-8b87-bb400bb9a994.png">

everything else is ok, but the tx text and value is fuzzy.   
Weird.

(and thank you for maintaining this tool-- I can not live without it)

-brewster
Internet Archive

**Comment by brewsterkahle** [comment]
Thank you for the new release!   but even with that, the transmit speed is not readable.

**Comment by yujitach** [comment]
Is there a problem even when you change the color in the preferences? Or do you want the color to be automatically changed to match the color of the menu bar?

There also is a new option in the "About" pane which allows you to mix in white/black depending on whether the menu bar is dark/light.

**Comment by ivan-kwok** [comment]
Hi Yujitach! I have a similar issue that network transmit text are always showing 0B/s but it shows the transmit rate correctly if I click on it. I tried the new white/black color tint option and it's still the same.

![Screen Shot 2020-11-24 at 11 29 27 AM](https://user-images.githubusercontent.com/51252282/100142792-4a5c8600-2e49-11eb-9c5c-99cfba0ae9f6.png) - Shows 0/Bs always

![Screen Shot 2020-11-24 at 11 30 44 AM](https://user-images.githubusercontent.com/51252282/100142893-5c3e2900-2e49-11eb-9c1a-38576156e0c6.png) - Shows correctly when mouse is clicked on it

**Comment by yujitach** [comment]
Dear @ivan-kwok , that's the issue discussed at length in #192. I'm having a trouble reproducing it on my Mac, so I haven't been able to fix it. 

By the way, how did you manage to show white icons on the menu bar on a light background? I would expect to have black icons on that background ...

**Comment by ivan-kwok** [comment]
@yujitach , that's right! #192 is the exact issue I'm having. Is there anything I can try to help you to track down the issue?
I have white icons and text on my second display only, don't really know why. The main display has regular black icons and text.

**Comment by yujitach** [comment]
@ivan-kwok Could you go to #192 and try the special debug build uploaded there? I would appreciate if you could report the result on #192 .

**Comment by brewsterkahle** [comment]
changing the colors in the preferences fixed it for me!  thank you.

**Comment by yujitach** [comment]
I'm glad that the problem is solved for you. Big Sur's menu bar changes have been very tricky to MenuMeters so far. By far the most difficult update, I say.
