### ISSUE TITLE
I just built the PrefPane but it doesn't show anywhere

### ISSUE THREAD

**Issue by piadam** [yujitach/MenuMeters#2]
Sorry to bother you but, as I was very happy to see your posting, I immediately tried to build your version of MenuMeters...
It was sad to find out that nothing showed up in my ~/Library/PreferencePanes... Build succeeded, no errors!
I tried to compile it on Yosemite 10.10.5 as wll as El Capitan 10.11 beta 8... Same results...

What could have gone wrong here?

Kind regards,
Adam

**Comment by yujitach** [comment]
Sorry for my slow reply. Did you build the target "PrefPane" ? Otherwise it won't work. Also, please use the latest Xcode beta.

**Comment by piadam** [comment]
Hello,

> On Sep 22, 2015, at 3:59 PM, yujitach <notifications@github.com> wrote:
> 
> Sorry for my slow reply. Did you build the target "PrefPane" ? Otherwise it won't work. Also, please use the latest Xcode beta.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

The answer to both questions is yes.

I did build PrefPane using the latest El Capitan-beta and the latest Xcode





Guess what… Today I DO have the file in my PreferencePanes…




Sorry to have bothered you… I’m sure I tried the same thing more than 5 times without succes and now… No clue…

Will no go and see if it works OK…

Thank you!!

Kind regards,
   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running OS X ‘El Capitan’ 10.11 beta)
--------------------------------------------------------------------
internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

HTML in email is a bad idea, see:
http://www.birdhouse.org/etc/evilmail.html
--------------------------------------------------------------------

**Comment by piadam** [comment]
Hello Yujitach,

You just made my day!!! I am so happy now!!!

Many, many thanks!!!

Kind regards,
   _
 /_/  _/  _   ___
/ / (_/ (_/ / / /
 Adam van Gaalen (running OS X ‘El Capitan’ 10.11 beta)
--------------------------------------------------------------------
internet: adam@vangaalen.homeip.net
internet: adam.vangaalen@icloud.com
http    : http://www.vangaalen.homeip.net

HTML in email is a bad idea, see:
http://www.birdhouse.org/etc/evilmail.html
--------------------------------------------------------------------

**Comment by yujitach** [comment]
Glad to know it worked.
