### ISSUE TITLE
CPU settings display options dysfunctional

### ISSUE THREAD

**Issue by MikeyDaBear** [yujitach/MenuMeters#20]
On latest public beta of El Capitan. The display CPU checkbox doesn't toggle on/off correctly, nor does the option to show average for multiple processors as single display work at all any more. Sometimes I really need that latter option to allow a number of menu items to display properly (even with consolidation with the Bartender app). I tried the Restart SystemUIServer script to see if it would influence the MenuMeter settings changes; it didn't.

<img width="586" alt="screen shot 2016-01-02 at 14 14 15" src="https://cloud.githubusercontent.com/assets/10860177/12076214/775e72ac-b15e-11e5-9040-1f12bf6880cb.png">
<img width="1440" alt="screen shot 2016-01-02 at 14 25 12" src="https://cloud.githubusercontent.com/assets/10860177/12076216/9c7e1eca-b15e-11e5-9c7f-b62f3b02bf5a.png">

**Comment by yujitach** [comment]
Thanks for reporting. As I don't have enough time to test the new beta myself, let me try to fix the bug once 10.11.3 become publicly available...

**Comment by pablolarrimbe** [comment]
Hey any news about this? I'm also seeing the same thing.

**Comment by fstutzman** [comment]
Issue seems to be resolved in 10.11.3 Golden

**Comment by MikeyDaBear** [comment]
@fstutzman I'm now on 10.11.4 beta (15E33e) and the issue is resolved.

**Comment by fstutzman** [comment]
:+1:

**Comment by MikeyDaBear** [comment]
Made it so. Thanks for helping me with GitHub etiquette!
