### ISSUE TITLE
Traffic statistics incorrect with L2TP IPSEC tunnel active

### ISSUE THREAD

**Issue by briantopping** [yujitach/MenuMeters#207]
Thanks so much for your continued commitment to this software!

I've noticed  MenuMeters 2.1.1 on Catalina when a L2TP IPSEC tunnel is active, the statistics for the primary interface shows only occasional traffic. With a stream running, the Rx numbers never go above zero.

Interestingly, MenuMeters shows the tunnel as "inactive", yet it has an IP address. See attached image.

Machine is a MacBookPro16,1, full network configuration is attached here: [full-network-config.txt](https://github.com/yujitach/MenuMeters/files/5676536/full-network-config.txt)

Please let me know if I can provide more information!

<img width="422" alt="Screen Shot 2020-12-07 at 8 05 34 PM" src="https://user-images.githubusercontent.com/158115/101434501-df3e9500-38c7-11eb-83ee-01a58699309a.png">

**Comment by yujitach** [comment]
What does the Activity Monitor show in this case?

**Comment by briantopping** [comment]
Closing after realizing this is likely to be an issue with the RealTek driver (surprised not surprised). When the WiFi is the primary connection as determined by OS routing, the display behaves correctly.
