### ISSUE TITLE
Most significant digit on temperature not displayed when set to F

### ISSUE THREAD

**Issue by Meterman84** [yujitach/MenuMeters#211]
I'm one of those uneducated hicks (read: Americans) who uses Fahrenheit.

Currently, I have the CPU temperature enabled among the displays and it says my CPU temp is a strangely low ~36.4 F (I played a graphics-intensive Flash game a few minutes ago), but switching to C reports a temperature of ~57 C.

So, the temperature display is clearly not allowing the hundreds digit to display when in Fahrenheit, and I SHOULD be seeing 136.4 F.

**Comment by yujitach** [comment]
Thanks, that's a good catch... I didn't expect to have more than 100 degrees.
