### ISSUE TITLE
Temperature error in 2.1.2

### ISSUE THREAD

**Issue by babauer** [yujitach/MenuMeters#216]
Hi-
After updating to 2.1.2, MenuMeters is now reporting that
the core temperature is 28.8F. (55.4C -which seems more accurate)
Have quit and restarted, and rebooted computer
iMac (Retina 5K, 27-inch, 2017)
10.15.7 (19H114)

<img width="146" alt="Screen Shot 2020-12-14 at 5 10 23 PM" src="https://user-images.githubusercontent.com/8194159/102141697-45c73400-3e2f-11eb-98f9-c392d047d844.png">

**Comment by yujitach** [comment]
Hi, this is the same with #211, merging it.
