### ISSUE TITLE
CPU Temperature display cuts off hundreds digit

### ISSUE THREAD

**Issue by dottedquad** [yujitach/MenuMeters#217]
In the latest version of MenuMeters there seems to be a problem in the display of CPU temperatures in F. Possibly all 3-digit temperatures? (even on C)

It makes temperatures in F seem 100 degrees lower than they should (53.4 C -> 28.0 F rather than 128.0 F)

**Comment by dottedquad** [comment]
Duplicate, sorry

**Comment by yujitach** [comment]
No problem, thank you for reporting.
