### ISSUE TITLE
No Temperature display on M1 Mac mini

### ISSUE THREAD

**Issue by tthkbw** [yujitach/MenuMeters#221]
using 2.1.2, the CPU temperature display is "??" I had seen this on the version of Menumeters I was using on a 2018 Mac mini. After checking, I saw that this new version of Menumeters had updates for Apple Silicon. Is temperature still not supported on Apple Silicon?

<img width="242" alt="NoTempMenuMeters" src="https://user-images.githubusercontent.com/6437525/102800559-e4402180-4368-11eb-89df-d28d2a4d9edb.png">

**Comment by dkbarto** [comment]
I also don't see any temperature on my M1 mini.

**Comment by yujitach** [comment]
We haven't figured out how to read off the temperature on Apple Silicon macs. The API we used before on Intel Macs no longer works.

**Comment by wrbluepearl** [comment]
I've noticed that other utilities that display CPU core temperatures aren't working with the M1 Mac Mini, for what it's worth.

**Comment by broxio** [comment]
I've run TG Pro (native) M1 , it can display temp.

**Comment by yujitach** [comment]
Ah, thanks. A quick googling gave me this: https://github.com/fermion-star/apple_sensors Apparently, an iOS code to get the temperature works on Apple Silicon macs ...
