### ISSUE TITLE
Temp overlaps CPU% when 12 cores are all running

### ISSUE THREAD

**Issue by dkbarto** [yujitach/MenuMeters#222]
<img width="73" alt="Screen Shot 2020-12-21 at 3 04 54 PM" src="https://user-images.githubusercontent.com/32245372/102830562-68f96280-439e-11eb-8cb7-d88def21526f.png">

Just a spacing issue, thought you'd like to know.
(And I don't get any temperature on my M1 Mac Mini either...)

**Comment by yujitach** [comment]
It should be fixed in the next release. The temperature issue is #221 .
