### ISSUE TITLE
CPU Usage percentage goes higher than 100%

### ISSUE THREAD

**Issue by sriharshachilakapati** [yujitach/MenuMeters#226]
When I try to open intensive apps, for example Android Studio, the usage percentage in the bar suddenly spikes to more than 100%, and sometimes hit 700% when I try to build a large project.

Interestingly, Activity Monitor only reports the use percentage at a max of 80% and goes back again. Using the latest version downloaded from GitHub releases on macOS Big Sur.

**Comment by yujitach** [comment]
What's the setting of the CPU meter? If your Mac has 8 cores and if you use the "sum of all CPUs" setting, the usage can go up to 800%.

**Comment by sriharshachilakapati** [comment]
My bad. Didn't realize that this was the default option. Sorry!
