### ISSUE TITLE
CPU temperature showing ??*C on Mac Pro 5,1

### ISSUE THREAD

**Issue by CornCat78** [yujitach/MenuMeters#227]
V2.1.2 and v2.1.3 do not show CPU temperature.
![image](https://user-images.githubusercontent.com/77812799/105756612-d1e27600-5f1a-11eb-8441-b2c7a25ec38f.png)

Other applications are reporting CPU temps correctly:
![image](https://user-images.githubusercontent.com/77812799/105756824-21c13d00-5f1b-11eb-8d94-55fa738dfc0d.png)

**Comment by yujitach** [comment]
Thanks, I kind of see where the bug lurks in my code. Which app did you use, by the way? How about https://github.com/exelban/stats ?

**Comment by CornCat78** [comment]
I'm using Hardware Monitor version 5.6.  It's pretty good software but unfortunately deprecated and no longer being updated:
![image](https://user-images.githubusercontent.com/77812799/105851749-7a431980-5fb1-11eb-977b-c61e48d43c72.png)

With regards to CPU temp not being shown in MenuMeters, oddly enough it works fine in MP3,1.  It's just the 5,1 that isn't being reported properly.  Perhaps the CPU temp sensor(s) isn't being correctly picked up in your code?

**Comment by yujitach** [comment]
Thanks, and yes that's exactly the problem. Macs have many sensors, and MenuMeters hard-code which sensor to display. Currently we use CPU 0 proximity sensor `TC0P` as listed in https://app.assembla.com/wiki/show/fakesmc . Most probably Mac Pro 5,1 doesn't have that particular sensor.

**Comment by CornCat78** [comment]
Interesting.  Thank you for clarifying.  Is this something that could possibly be fixed or a work-around found in the next release? Obviously it's not a show-stopper for me and your application does for the most part, everything else I need it to do. But, it would be nice to have either way.  In the interim, I've simply disabled CPU temp readout.

**Comment by yujitach** [comment]
Thanks for the info. That’s very helpful. The problem for me is to figure out the four-letter internal code for the sensors you have. Could you post the screenshot of the “sensor” customization tab of the app https://github.com/exelban/stats ? That would be more helpful, since it is open source. 

In general, if you run modern enough macOS versions, I recommend you to use stats instead of MenuMeters. It is more modern-looking and more actively maintained.

**Comment by CornCat78** [comment]
Here is the sensors page from the Stats app (v2.4.14). I'm not seeing an option to customize sensors, or see the sensor internal code:
![image](https://user-images.githubusercontent.com/77812799/105985585-a4f0a900-6069-11eb-9c13-48bd16ef191f.png)

**Comment by yujitach** [comment]
Hi, I made a new pre-release version which  hopefully fixes the issue. There are multiple temperature sensors, so you should now be able to choose one which you'd like to use. Could you try https://github.com/yujitach/MenuMeters/releases/tag/2.1.4 ? I would appreciate if you could upload the screenshot of the CPU pref pane, with the list of the available temperature sensors expanded by clicking on it.

**Comment by CornCat78** [comment]
Sorry for the late reply. I will test this tomorrow during the day and revert with the results. Many thanks for your efforts thus far!

**Comment by CornCat78** [comment]
Hello again.  Please see attached screen shots.  Temp readout in menubar seems to work although I'm unsure as to which sensor is for what.  Would you happen to have a list?
![Screen Shot 2021-02-01 at 06 46 42](https://user-images.githubusercontent.com/77812799/106454969-8a4b7500-6459-11eb-818f-0954c244d0b9.png)

And the menu bar:
![image](https://user-images.githubusercontent.com/77812799/106455080-b49d3280-6459-11eb-87ed-3f1a249833e2.png)

**Comment by yujitach** [comment]
Wow, that's a lot of sensors, a lot more than my MacBook Pro and Mac Mini. Unfortunately it's hard to tell exactly which four-letter combination corresponds to which sensor for what purpose. `T` at the beginning seems to stand for temperature, and `TC??` seems to be for CPU temperatures.  

These information is not publicly available from Apple, and I instead rely on various open source codes written by those who reverse-engineered some of them, and what is shown in MenuMeters is all what I can gather at this moment. 

Thank you very much for your help. I will release this version later today.

**Comment by CornCat78** [comment]
No, thank you for modifying the software to accommodate!  It's much appreciated.  No worries on the sensor list.  It's easy enough to compare the output provided by MenuMeters against other applications.  In my case, TCBD appears to be the actual temperature diode readouts for CPU2, and TCAD for CPU1.  

This is the list HW monitor provides so it's just a matter of matching temperature readouts at this point:
![Screen Shot 2021-02-01 at 08 16 49](https://user-images.githubusercontent.com/77812799/106463960-077ce700-6466-11eb-96c9-8a4d77eb3c1b.png)

**Comment by yujitach** [comment]
Thanks, I wonder how the HW monitor obtains the human-readable sensor names. Maybe I should ask the developer. As the app is discontinued, there shouldn't be any problem for the developer to tell me how to obtain the info...

**Comment by CornCat78** [comment]
That would be nice if they could give that to you.  I'll keep my eye on this thread in case you are able to update it down the road.  Have a great day!
