### ISSUE TITLE
Rx always = 0 on 10Gb interface

### ISSUE THREAD

**Issue by cnolanh** [yujitach/MenuMeters#235]
I'm using MenuMeters 2.1.4 on macOS 10.15.7 on a 27-inch 2013 iMac. MM works as expected except that once I added a Sonnet Echo Express SEL 10Gb ethernet adapter (connected via Thunderbolt), MM only reports Tx activity on this interface. Rx stays at 0 no matter what I do. Rx does show properly for the iMac's built-in 1Gb ethernet port.

I've tried "Display this interface" and "Display primary interface," and I've tried using both of the 10Gb ports on the Sonnet adapter. No change. I have the most recent Sonnet driver installed for this 10Gb adapter. The network interface does work solidly and passes traffic both directions.

Thanks for any help! I'd really like to be able to monitor my incoming network speeds with this 10Gb connection. And one more clue: Activity Monitor in macOS also does not show me any Rx stats for the 10Gb interface.

**Comment by cnolanh** [comment]
And just now I see that issue #143 seems to be the same problem I'm encountering. Sorry about not finding that earlier.

**Comment by yujitach** [comment]
Indeed that's the issue. It's hard to go around this bug if it's not reported in the system-provided Activity Monitor either...
