### ISSUE TITLE
Upload and download arrows misplaced

### ISSUE THREAD

**Issue by rajaspidey** [yujitach/MenuMeters#236]
Network monitor is showing UP arrow for DownloadSpeed and DOWN arrows for UploadSpeed

<img width="93" alt="Screenshot 2021-02-17 at 11 43 47" src="https://user-images.githubusercontent.com/1059186/108163928-d7943b80-7115-11eb-851e-723e19fbdc4d.png">

**Comment by yujitach** [comment]
That can be changed in the preferences. 
![Screen Shot 2021-02-17 at 15 21 50](https://user-images.githubusercontent.com/5449811/108164372-002b2e00-7134-11eb-90b6-8f5300c3c261.png)
