### ISSUE TITLE
my upload speed is showing up as 212Mbps while my internet is just 100Mbps

### ISSUE THREAD

**Issue by rajaspidey** [yujitach/MenuMeters#237]
my upload speed is showing up as 212Mbps while my internet is just 100Mbps. I thought, maybe am getting better speeds but then I noted 'Tx' went upto 158GB while am just uploading a 34GB file. and just  30% of the file was uploaded to YouTube 

![Screenshot 2021-02-26 at 08 34 49](https://user-images.githubusercontent.com/1059186/109249567-eeb9e400-780d-11eb-88d4-60e36c3599c5.png)

**Comment by yujitach** [comment]
I believe this is the same one as #190 . It's annoying but seems to be due to a buggy driver...
