### ISSUE TITLE
MenuMeters needs to be code-signed?

### ISSUE THREAD

**Issue by wardoldham** [yujitach/MenuMeters#246]
I'm using Menumeters 2.1.4 running under OS X 10.11.6 (El Capitan). Periodically I get this cryptic dialog box (attached). It does not impact Menumeters running nor its functionality (I don't think!)

Please advise.
![Screen Shot 2021-07-16 at 9 22 14 AM](https://user-images.githubusercontent.com/87504719/125961566-3b17221a-62b4-4e69-9e7f-c042fedf8b3c.png)

**Comment by wardoldham** [comment]
I have to let everyone know, I contacted Yuji via email and this guy is a pure pleasure to converse with. Needless to say, downloading the software from the link he provided solved my issue! :)

**Comment by fleish** [comment]
@wardoldham or @yujitach can one of you provide more details on the conversation and what link is being referred to? The Sparkle project link seems to be something the code developer would use for signing during the build/packaging process, so I'm guessing that's not what would be downloaded by the end user.

**Comment by yujitach** [comment]
@fleish Do you see the same dialog? The issue is fixed (I think) in the latest version, so you don’t have to worry about it.

**Comment by fleish** [comment]
@yujitach yes, I got the same pop-up message on an M1 mac Mini install running Monterey

**Comment by yujitach** [comment]
Which version of Men,uMeters did you install, and from where did you get the binary?

**Comment by fleish** [comment]
The Info.plist file lists version `2.1.6.1` and it was downloaded from https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ on Feb 9

**Comment by yujitach** [comment]
Hmm, that's very strange. Other users haven't seen the same codesign issues for that version. Could you download it again from https://github.com/yujitach/MenuMeters/releases/tag/2.1.6.1 ?

**Comment by fleish** [comment]
That looks like the same file I have:
```
MD5 (MenuMeters_2.1.6.1.zip) = 34a09d8d549989bff1e51719ba5a3139
MD5 (MenuMeters_latest.zip) = 34a09d8d549989bff1e51719ba5a3139
```

And the extracted app file also seems to match, save for the non-regular files (symlinks):
```
rsync -cvrn Downloads/MenuMeters.app /Applications
building file list ... done
skipping non-regular file "MenuMeters.app/Contents/Frameworks/Sparkle.framework/Resources"
skipping non-regular file "MenuMeters.app/Contents/Frameworks/Sparkle.framework/Sparkle"
skipping non-regular file "MenuMeters.app/Contents/Frameworks/Sparkle.framework/Versions/Current"

sent 4487 bytes  received 20 bytes  9014.00 bytes/sec
total size is 4606727  speedup is 1022.13
```
