### ISSUE TITLE
CPU Percentage color is black even with a dark desktop color

### ISSUE THREAD

**Issue by aafisher** [yujitach/MenuMeters#247]
Hi. First off, great job porting the project and keeping it alive.

Being that I do a lot of color correction on images, I keep my desktop a dark, neutral gray color. All the icons in my menubar are white, except for the MM combined CPU percentage indicator, which is black. Black on dark gray is not very readable. In the MM control panel, the color of this item is not user-selectable, which would solve the problem. On the CPU pane, only colors for graph and thermometer are user-selectable, not the percentage.

**Comment by yujitach** [comment]
Please post the desktop picture, or please tell me the color in hex.

**Comment by aafisher** [comment]
![cpu-percentage](https://user-images.githubusercontent.com/11027076/127356728-ba996b4d-7a20-4a26-8434-151eb759aff8.jpg)
Example

**Comment by yujitach** [comment]
Sorry for not replying sooner. I think this is fixed at the same time when I fixed https://github.com/yujitach/MenuMeters/issues/258 .
