### ISSUE TITLE
Showing Incorrect Free Memory when Your code using according to IPhone 6

### ISSUE THREAD

**Issue by preen27** [yujitach/MenuMeters#25]
Hi,, i want to ask you that when Your code i am using for iPhone 6  Free memory state then sometime its showing Free memory greater then The Total  memory   like: My Total ram is - 989  and And Free ram is 1.29 GB  and Some time its Showing Correct data and its working Fine, please tell whats going wrong there then i can identify what i am doing wrong

**Comment by fstutzman** [comment]
The issue may be due to [memory compression](http://macs.about.com/od/macoperatingsystems/fl/Understanding-Compressed-Memory-in-OS-X.htm), but to investigate this it would be useful to provide a replication case.

**Comment by preen27** [comment]
vm_statistics64_data_t vmStats64;
    bzero(&vmStats64, sizeof(vm_statistics64_data_t));
    // HOST_VM_INFO64_COUNT
    mach_msg_type_number_t vmCount = (mach_msg_type_number_t)(sizeof(vm_statistics64_data_t)/sizeof(integer_t));
    mach_port_t  selfHost = mach_host_self();
    if (host_statistics64(selfHost, 4 /* HOST_VM_INFO64 */, (host_info64_t)&vmStats64, &vmCount) != KERN_SUCCESS) {
        return;
    }
    // Memory page statistics
    //unsigned int *add = &vmStats64.active_count;
    double active = vmStats64.active_count * vm_page_size;
   double inactive = vmStats64.inactive_count * vm_page_size;
   double wired = vmStats64.wire_count * vm_page_size;
   double freeMem = vmStats64.free_count * vm_page_size;

   NSLog(@"Here Is Free Memmory *** and *****  page size is %f   %u ",freeMem,vm_page_size);

  when I print This its showing me Page Size --                16384   and because of this Free memory is incorrect

**Comment by yujitach** [comment]
This is not really an issue about MenuMeters, rather an issue concerning a snippet of code from MenuMeters not working as naively expected on iOS. I suggest @preen27 to ask it on http://stackoverflow.com if it's not resolved yet. I close this as an issue of MenuMeters.
