### ISSUE TITLE
Temperature text color inconsistent

### ISSUE THREAD

**Issue by udirub** [yujitach/MenuMeters#258]
Hello,

I've set the temperature text color to labelColor but it doesn't always change like the CPU usage text's color change when the system changes the color of the menu bar.
<img width="120" alt="Screen Shot 2021-10-30 at 18 11 45" src="https://user-images.githubusercontent.com/5929721/139538912-74bcdf87-ff41-4305-a7ac-1ae0fb6a33a0.png">
I'm running macOS 12.0.1 on the new 16" M1 Pro.

**Comment by schriftgestalt** [comment]
How do you get the toolbar swich to Light mode? Mine always uses white text.

**Comment by udirub** [comment]
When you set a dynamic desktop wallpaper it changes the color of the toolbar as the desktop changes.

**Comment by schriftgestalt** [comment]
I tried that but it didn't for me. I’ll have a look.

**Comment by udirub** [comment]
It also happens when I play a movie in full screen. 
The text in the menu bar is white when in the movie and turns back to black when exiting the movie.

**Comment by schriftgestalt** [comment]
The thing is my text was always white. I had tried with the lightest background image I could find. Now I tried again with a plain color and I see the effect. 
And picking a custom color is indeed strange. It seems to do the opposite then what I would expect. So for me, picking "textBackgroundColor" seems to work as expected. 

I found the ‘Color tint’ setting in the About settings very nice. Sliding it all the way to the right looks nice (with my adjusted drawing).

**Comment by udirub** [comment]
Yeah, I noticed that sometimes it works in reverse for some reason. I set it to a color that should be black and it turns out white. But after a restart it switched back to the right order.
The color tint does look nice. I'll give it a try and see if it remains consistent.

**Comment by yujitach** [comment]
Should be fixed in https://github.com/yujitach/MenuMeters/releases/tag/2.1.6 .
