### ISSUE TITLE
CPU power limit (null)

### ISSUE THREAD

**Issue by almanza-d** [yujitach/MenuMeters#263]
Is there a way to toggle the CPU power limit that currently shows "null". Is this as intended? Do not recall same issue on previous intel Macbook pro. 

[Here a picture of what I am referring to](https://imgur.com/a/bYFbI5J)

**Comment by yujitach** [comment]
CPU power limit is not available on Apple Silicon Macs. That entry should be removed on Apple Silicon Macs in the next release.

**Comment by yujitach** [comment]
Should be fixed in https://github.com/yujitach/MenuMeters/releases/tag/2.1.6 .
