### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by yticolev** [yujitach/MenuMeters#28]
Long time Snow Leopard user of Menu Meters who just bought a new MacBook. Thanks for updating this for El Capitan. I've just installed it and it works fine - I did try the original installer a few days ago and yes, completely incompatible. I easily removed it using the installer (but I could have removed it manually instead in Library>PreferencePanes). I cannot find how to remove your version nor can I find its location.

I have an enhancement request, is it possible to remove the CPU hit for monitoring options not needed? I know this is minor, but over sometimes several days without access to power, the battery life hit can be significant. Perhaps with the same checkbox used to toggle display. I played with extending the update intervals on unused items to no effect. Playing with intervals revealed a CPU use with a minimum of around 2% as measured by the activity monitor that I could not drop further.

Thanks!

**Comment by ecovaci** [comment]
Go to "System Preferences", you'll see MenuMeters panel. Right click then select Remove.

**Comment by yticolev** [comment]
Thank you! That's easy.

**Comment by retrography** [comment]
@yticolev Or simply use [AppCleaner](https://freemacsoft.net/appcleaner/) (for any uninstall process)

**Comment by yticolev** [comment]
Thanks for that. I'll give it a try for some other cleanup work.

**Comment by youtubismify** [comment]
Hi everyone. I installed this port on my mac and have decided to uninstall it. I have followed the above instructions and have successfully removed the menumeters preferences pane from system settings (and it is not showing in Library/PreferencesPanes and ~/Library/PreferencesPanes).

However, having restarted the mac, the menu icon is still present in the menu bar. Is there any further advice you could give me as to how I can try to remove the port from my device? App Cleaner does not seem to be able to 'see' anything relating to menu meters. 

Thank you in advance.

**Comment by cambecc** [comment]
Same issue as @youtubismify. Removing the preference pane from System Preferences does not actually stop MenuMeters from running on startup. And if you repeat install process, the meters get duplicated:
<img width="271" alt="screen shot 2016-12-30 at 2 07 20" src="https://cloud.githubusercontent.com/assets/3368530/21549312/beea071e-ce34-11e6-97e5-76a7e1b32b50.png">

**Comment by cambecc** [comment]
Found the reason: despite removing the preferences pane, 1) MenuMetersApp is still listed in `Users & Groups->your user->Login Items`, and 2) MenuMetersApp is still on disk sitting in the trash. So make sure to empty the trash and remove MenuMetersApp from your set of login items.

**Comment by yujitach** [comment]
I updated the instructions accordingly: http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ 

Thanks for the comments.

**Comment by nitinnain** [comment]
You should mention this step --  "MenuMetersApp is still listed in `Users & Groups->your user->Login Items`", from cambecc's answer on http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ too.

**Comment by yujitach** [comment]
I believe emptying the trash suffices.
