### ISSUE TITLE
Opened Menu Meters on new M1 Macbook Pro and it doesn't display anything...

### ISSUE THREAD

**Issue by jdiamondGitHub** [yujitach/MenuMeters#288]
Just downloaded the latest version. All the settings dialogs run fine, but absolutely nothing shows up on the task bar.  Is there a missing step you need to do so menu meters would display in the menu bar?  At the moment, menu meters seems to do nothing at all.

Thanks for any thoughts.
- Jeff
-

**Comment by jdiamondGitHub** [comment]
Update:  After a few relaunches, menu meters is displaying on the menu bar now!  Yippie!  Thanks for such a wonderful program.  I was surprised to see that my M1 Max does all it can to only use the 2 efficiency cores, and that the efficiency cores are running at 3.7 GHz!

This is an amazing program!  Thanks so much for updating it.

**Comment by yujitach** [comment]
Thanks for your report. Many users of new MacBook Pros with notches say they have problems. I'd like to fix it, but unfortunately I don't have those new MacBook Pros ...
