### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by slambert73** [yujitach/MenuMeters#3]
I just installed El Capitan and your build of menu meters. I choose to instal the pref pane for all users. When I try to click to engage a menu I get the error: "Menu Extra Could Not Load."

I deleted and installed for single user only. I can check the box to turn on a menu, but nothing happens when I come back the box is unchecked again.
![screen shot 2015-09-30 at 5 21 48 pm](https://cloud.githubusercontent.com/assets/14915110/10207229/17e507fa-6799-11e5-8e23-d48dfe088fcf.png)

UPDATE
Tried a third (single user only). It seems to work.

**Comment by cvn** [comment]
I think your old .prefpane was still getting loaded, even though it was in the trash. I had to quit and restart the System Preferences app to get it to load the new version.

**Comment by slambert73** [comment]
Must be. When I got your version working I could see ver 1.9 instead of 1.8.1 (I thought it strange that you didn’t increment the version.) Thanks I am enjoying your app!

-Scott

**Comment by cvn** [comment]
I'm just a fellow user, not the author. Thanks go to Alex Harper for writing it and @yujitach for the port.

**Comment by yujitach** [comment]
Thanks for solving the problems by yourselves :)
