### ISSUE TITLE
[Feature Request] Select Monitor for MenuMeters

### ISSUE THREAD

**Issue by DD1TTY** [yujitach/MenuMeters#307]
Currently MenuMeters shows up in the status bar of all connected displays. It would be slick if there were a toggle or selector to specify only one (or more) displays to show MenuMeters.

**Comment by yujitach** [comment]
> Currently MenuMeters shows up in the status bar of all connected displays. It would be slick if there were a toggle or selector to specify only one (or more) displays to show MenuMeters. 

That would be nice, but I don't think macOS supports it in the first place.

Is there any other menu bar app which shows up only in a single display, not on all menu bars on all displays? If there is an example out in the wild, I might be able to try and mimic the behavior...
