### ISSUE TITLE
Load average(s) indicator

### ISSUE THREAD

**Issue by kvelicka** [yujitach/MenuMeters#32]
I'd be very interested in having a menu meter that displays the load average(s) for the system. Would that be a difficult feature to add to MenuMeters?

**Comment by onpaws** [comment]
![image](https://cloud.githubusercontent.com/assets/182515/18444569/c2f360aa-78e7-11e6-84ba-3c44c659fac6.png)
I can see the load averages on the CPU meter on El Capitan. You?

**Comment by kvelicka** [comment]
My bad for inaccurate wording - I can see them in the context menu of the CPU meter but I was wondering if I could have them together with/instead of the meter itself in the tray (just like I can have CPU percentage).

**Comment by onpaws** [comment]
It would be a matter of dropping `[cpuInfo loadAverage]` into the top-level.
This looks like a good place to [start](https://github.com/yujitach/MenuMeters/blob/master/MenuExtras/MenuMeterCPU/MenuMeterCPUExtra.m#L394)

**Comment by kvelicka** [comment]
I'll have a look into it. Thanks for the starting point!

**Comment by kvelicka** [comment]
In case someone is looking to do something similar, https://github.com/matryer/bitbar can be used to display the output of arbitrary bash commands in the menu bar. For load averages, this works:

```bash
#! /bin/bash

uptime | awk '{split(substr($0, index($0, "load")), a, ":"); print a[2]}'
```
