### ISSUE TITLE
macOS Sierra Support

### ISSUE THREAD

**Issue by mikescott** [yujitach/MenuMeters#34]
When I try and open the preference pane in Sierra I get the following error:

"Preferences Error

Could not load MenuMeters preference pane."

Are there any plans for an update that introduces support for macOS Sierra?

**Comment by pi1ot** [comment]
v1.9.2 works fine for me on osx 10.12

**Comment by rotexhawk** [comment]
I am getting the same message. Not working at all.

**Comment by hotsupport** [comment]
Works fine for me on macOS Sierra 10.12.2

**Comment by jsmayo** [comment]
Working for me as well. Make sure you go into System preferences and open the MenuMeter options, then double click the prefPane. If you get the error again, close system preferences, open it again, and then it should work. At least it did for me :]

**Comment by marcozink** [comment]
Had the same problem with MacOS Sierra 10.12.6, followed the steps from @jsmayo which did not work for me. I found [this port](https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/) and everything is now working.
