### ISSUE TITLE
Sierra: Command-dragging works

### ISSUE THREAD

**Issue by onpaws** [yujitach/MenuMeters#36]
As explained [elsewhere](https://9to5mac.com/2016/06/18/macos-sierra-rearrange-third-party-menu-bar-icons/),  as of Sierra 10.12, macOS supports command-dragging 3rd party menu items (NSStatusItems), including this lovely fork.

Considering the existence of [MenuCracker](/perfaram/MenuCracker) was for precisely this purpose, it's nice to see support officially finally land after all these years.

@yujitach Happy to send a PR to update the [read me](http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/) if you'd like -- please just point me in the right direction.

**Comment by yujitach** [comment]
I just updated the read me at my webpage, thanks for the suggestion.
