### ISSUE TITLE
WindowServer (resource leaks?)

### ISSUE THREAD

**Issue by rcarmo** [yujitach/MenuMeters#37]
When MenuMeters is left running over several days, I notice that WindowServer starts taking up more and more CPU load, to the extent where my Mac becomes extremely slow.

Going into the preference pane and toggling each display immediately releases whatever resources are tied up, with visible results in Activity Monitor.

This is happening in OS X Sierra 10.12.1. It might not be immediately noticeable in modern machines, but on a six-year-old Mac mini it effectively cripples the machine in two days of uptime.

**Comment by Haijuk** [comment]
Have several machines (MacBook Pro 2010, MacMini 2012, iMac 2013) running on ElCap 10.11.6 and no issues so far. I only throttled down disk update intervalls from 0.3 to 0.7/s as it may slow down the machines, especially with network disks. Well, not a solution for you but maybe it points to Sierra.

**Comment by yujitach** [comment]
Could you post the screenshot of Activity Monitor when this happens? That would help me identify the problem.

**Comment by Haijuk** [comment]
@yujitach:
(OffTopic)
Thanks for taking your time for this tool. As soon as I'm better with Bitcoin knowledge, I would pay for your effort to keep this alive. Its great to see people around like you.

**Comment by rcarmo** [comment]
Sure, but all that's visible in that screenshot is WindowServer hogging the CPU. MenuMeters hardly shows up on either CPU or RAM use, so I don't understand how the screenshot will help.

**Comment by yujitach** [comment]
If that's the case I don't think I can help... I only have the source code for MenuMeters, not for WindowServer which is secretly maintained by Apple ...

**Comment by yujitach** [comment]
Unfortunately with this much info I don't think I can help.
