### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by djp3** [yujitach/MenuMeters#4]
Thanks for porting this!

**Comment by mfriedenhagen** [comment]
+1

**Comment by princefisher** [comment]
Thank you! *thumbs up* for the port!

**Comment by benzwu** [comment]
+1

**Comment by ralexx** [comment]
Thanks Yuji.

**Comment by ranek** [comment]
Thanks!

I like using Homebrew Cask to install software, so I've submitted a pull request to add your version as an option: https://github.com/caskroom/homebrew-cask/pull/14145

If merged, this will make it easy for Homebrew Cask users to install your fork simply by typing `brew cask install yujitach-menumeters`.

**Comment by easye** [comment]
+1 Thanks so much!

**Comment by albertyw** [comment]
+1

**Comment by tomasmcm** [comment]
+1

**Comment by vitorgalvao** [comment]
> If merged, this will make it easy for Homebrew Cask users to install your fork simply by typing `brew cask install yujitach-menumeters`.

Merged now. Don’t forget to `brew upgrade` before trying to install.

**Comment by BlackBrane** [comment]
Extremely glad to have this fix. Thanks!

**Comment by rlincke** [comment]
Thank you as well for the fix. Thats great!

Would it actually be possible to provide Menu Meters officially in the Apple App Store? What would be needed for doing this (I am happy to sponsor any Apple Developer fee).

**Comment by skyfaller** [comment]
Thank you so much! This is literally the first program I download when I gain control over an Apple computer (rapidly followed by Chrome or Firefox), I hate not being able to see what the computer is doing behind the scenes. Hopefully you and the original developer can work together to keep MenuMeters updated and available in the future.

**Comment by nrichards** [comment]
Thank you Yuji Tachikawa !!

**Comment by koppacetic** [comment]
+1!!!
Dude, you rock! Thank you!

**Comment by steffenagger** [comment]
Thank you! (+1)

**Comment by ikuwow** [comment]
問題なく動きます。ありがとうございます！！
It works fine. Thank you so much!!

**Comment by borestad** [comment]
Awesome initiative & great work!!

As someone suggested, a merge might be possible into the original project.

**Comment by c0rnflex** [comment]
Cheers!

**Comment by biziclop** [comment]
+9!

**Comment by bongotai** [comment]
Thanks man you are the best! I can't live without Menu Meters :-)

**Comment by andreasfaerber** [comment]
Thanks! Appreciated!

**Comment by Huitzilo** [comment]
Thank you for making this effort. Three cheers for Open Source and the GPL!

**Comment by rlazoti** [comment]
Awesome!
Thank you. :+1:

**Comment by XavM** [comment]
+1

**Comment by henrythroop** [comment]
Thank you!!!

**Comment by drosen0** [comment]
+1

**Comment by deepj** [comment]
:+1:

**Comment by hgrubbs** [comment]
Thanks, I really appreciate your effort.

**Comment by fhorlaville** [comment]
Thank you very much !!!!

**Comment by tiagoamaro** [comment]
+1

**Comment by jalessio** [comment]
Open Source FTW! Thank you @yujitach! And thanks to @ranek for getting it into Homebrew!

**Comment by Moi-FR** [comment]
Juste énorme!!!
Grand merci pour cette astuce! :)

**Comment by jordan314** [comment]
Thank you!

**Comment by abajo** [comment]
Thank you !!!!!!!!!

**Comment by sambuc** [comment]
Thank you!

**Comment by Pablofp** [comment]
Thank you!! Muchísimas gracias!!!

**Comment by kyndder** [comment]
Thank you!

**Comment by cpauya** [comment]
+1 Thank you! :smile_cat:

**Comment by mhzed** [comment]
You are the best!

**Comment by Qandelor** [comment]
Thank you!

**Comment by mackonsti** [comment]
Despite all the issues with El Capitan, thank you for porting this tool and thanks to the original author for making it available on GitHub!

**Comment by zhangcheng** [comment]
Thanks for making this happened.

**Comment by teras** [comment]
+1

**Comment by sheavner** [comment]
:+1:

**Comment by rjdrost** [comment]
Awesome!!! Thank you so much for your efforts!

**Comment by eichstaedtPTB** [comment]
+1

**Comment by itsmeonline** [comment]
thank you!

**Comment by mkecman** [comment]
You just made my day! Thank you so much for this port!

**Comment by u2mejc** [comment]
Another :+1:, install from home brew too.

**Comment by sandhub** [comment]
:+1:

**Comment by fstutzman** [comment]
:+1:

**Comment by diggeridoo** [comment]
Thank you! :clap:

**Comment by tmohme** [comment]
Thank you!

**Comment by bevankoopman** [comment]
Woot!

**Comment by focs** [comment]
Thanks a lot!

**Comment by yunarsoa** [comment]
Thank you for porting this to El Capitan!

**Comment by lababidi** [comment]
Thank you!

**Comment by justperry** [comment]
I always preferred MenuMeters over iStatMenus, luckily I found this, so glad it works again, thanks a lot for taking the time to code it so that it works again.

Cheers

**Comment by Haijuk** [comment]
Sir, you made my day! Thanks a lot!

**Comment by eshizhan** [comment]
LGTM, Thanks😸

**Comment by skywinder** [comment]
It's amazing tool! Thanks!

**Comment by fredprod** [comment]
Great tool even working on MacOS Sierra

**Comment by mihigh** [comment]
👍  Thank you.

**Comment by Haijuk** [comment]
Well, lots of people say thank you. Of course I do too. How about giving this man some beers at least?
@yujitach: Give us a Bitcoin address to show our respect to your effort. (If there's one already I might have missed, please point me to and blame me)

**Comment by mcr-ksh** [comment]
+1

**Comment by myint** [comment]
Thanks!

We're in the process of switching the MacPorts port of MenuMeters from `ragingmenace.com` to this repository.

https://github.com/macports/macports-ports/pull/489

**Comment by victordev** [comment]
Thanks <3

**Comment by wjcroft** [comment]
Yuji, thanks so much. Very impressed also with your physics research and professorship at Kavli ! 

https://member.ipmu.jp/yuji.tachikawa/

**Comment by unnawut** [comment]
Thank you!

**Comment by rdp** [comment]
+1 from me, you should add a donate button :)

**Comment by mgulsoy** [comment]
+1 from me. Thank you.
