### ISSUE TITLE
meters appear several times

### ISSUE THREAD

**Issue by gramels** [yujitach/MenuMeters#40]
I have now 4 times each menubar display for each item I enable.
How do I get back to one?
Might be upgrade leftovers but dont know where to fix this.

**Comment by yujitach** [comment]
Please empty the trash and reboot (or logout and login) once.

**Comment by yujitach** [comment]
I updated the instructions accordingly: http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/

Thanks for the comments.
