### ISSUE TITLE
Feature request: display memory pressure

### ISSUE THREAD

**Issue by geigi** [yujitach/MenuMeters#43]
I just tried a different app for displaying cpu and memory information in the menubar and it had an option to show the current memory pressure (as in Activity Monitor) instead of the actual used/free memory. I really liked that, would it be possible to implement this in MenuMeters?

**Comment by yujitach** [comment]
Which app? It's definitely possible and easy. However, unfortunately, I don't have enough free time these days to implement new features. I hope somebody to contribute the code.

**Comment by geigi** [comment]
The app is called MenuBar Stats from the App Store. Cheers, maybe I will find time for this sometime :)

**Comment by yujitach** [comment]
Merged @geigi's contribution and issued the new release v1.9.4. Issue closed. Many thanks to @geigi .
