### ISSUE TITLE
duplicated entries

### ISSUE THREAD

**Issue by dputnam12002** [yujitach/MenuMeters#48]
I am seeing duplicated entries fro everything
![screen shot 2017-02-28 at 8 16 32 pm](https://cloud.githubusercontent.com/assets/26104233/23445775/d6186ca8-fdf2-11e6-918f-529059049d53.png)

**Comment by onpaws** [comment]
You probably have two instances of MenuMeters running - check Activity Monitor for `MenuMetersApp` and kill one.

**Comment by yujitach** [comment]
Duplicate of #68. #68 is newer but has a more detailed workaround posted, so I close this one.
