### ISSUE TITLE
Update Interval seems to be Ignored

### ISSUE THREAD

**Issue by fdinoff** [yujitach/MenuMeters#5]
I'm using the Memory Menu Meter and have the update interval set to 10 seconds. However it doesn't seem to be respected. The menu seems to get updated every second.

**Comment by yujitach** [comment]
I pushed a quick fix. Could you test it? To enable the new version, you need to kill MenuMetersApp.app from Activity Monitor (or by logging out and loggin in again.) The menu meters don't dynamically respond to the timer interval changes in the pref pane either; you need to remove the menu meter and reenable it by unchecking and checking the checkbox. Once it's reflected, it should persist across the login.

**Comment by fdinoff** [comment]
I don't see a difference. (I used http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.zip)

**Comment by yujitach** [comment]
I haven't changed that binary. Could you "git clone" and test it?

**Comment by fdinoff** [comment]
I'm not sure how to build the project.

**Comment by yujitach** [comment]
Please just build the "PrefPane" target. That should automatically put the compiled .prefPane to Library/Preference Panes so that System Preferences.app notices it.

**Comment by fdinoff** [comment]
I don't think anything changed. (I built the project the PrefPane target in Xcode and logged out and back in)

**Comment by yujitach** [comment]
I'm super sorry. I forgot to push the relevant code changes ... oh my ...

**Comment by ta-cameron** [comment]
Update intervals now appear to be working as expected with this update (at least for me). Thanks!

**Comment by fdinoff** [comment]
Thanks. Seems to work.
