### ISSUE TITLE
Version 1.9.4 download reports 1.9.3

### ISSUE THREAD

**Issue by rectalogic** [yujitach/MenuMeters#55]
The prefPane inside the 1.9.4 download zip reports it is version 1.9.3
http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.4.zip
![screen shot 2017-04-04 at 11 33 54 am](https://cloud.githubusercontent.com/assets/11581/24665195/a24a78e6-192a-11e7-8832-44e62f206c74.png)

**Comment by yujitach** [comment]
Thanks. It's fixed in 1.9.5, thanks to @emcrisostomo's contribution.
