### ISSUE TITLE
⌘-dragging does work

### ISSUE THREAD

**Issue by daveyostcom** [yujitach/MenuMeters#58]
http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ says:

> One good thing about the former is that you can rearrange them by ⌘-dragging the menu items. I have no idea why ⌘-dragging is not provided for the latter by the system.

Just tried this on 10.12.4. ⌘-dragging reorders NSMenuExtras and NSStatusItems as desired, and the ordering persists across logout.

**Comment by yujitach** [comment]
Please have a look at the last paragraph of that page, where the same thing was mentioned. Thanks very much nonetheless; I should move that paragraph to somewhere closer to the top. Will do when I have the time.
