### ISSUE TITLE
10.13 beta - non functional

### ISSUE THREAD

**Issue by mrgoot** [yujitach/MenuMeters#59]
Hello,

The preference pane is there in system preferences.  When clicking on let's say "Display Network Menu Meter" - about 10 seconds later a popup happens:

"Menu Extra Could Not Load"
For instructions on enabling third-party menu extras please see the documentation.

console.log says default

	21:02:22.917911 -0400	SystemUIServer	invalid menu extra: /Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuCracker.menu
default	21:02:22.918020 -0400	SystemUIServer	unable to load menu extra: /Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuCracker.menu

**Comment by yujitach** [comment]
I haven't tested 10.13 beta yet, but I'm pretty sure that the version of MenuMeters you tried to install was a rather old one from http://ragingmenace.com. Could you try the one available at https://github.com/yujitach/MenuMeters/releases ?

**Comment by mrgoot** [comment]
Thank you for your reply.  I was using version 1.7.  I have updated to version 1.9.5.  

MenuMeters has launched and has full functionality.  Have you considered a version checker somewhere?

**Comment by yujitach** [comment]
Thank you for checking. I've considered a version checker, but  I haven't implemented it. In addition, v1.7 was developed by the original developer of MenuMeters which was abandoned and I took over the development. So there's no way for me to add the version checker in v1.7 ...
