### ISSUE TITLE
Could not load MenuMeters preference pane.

### ISSUE THREAD

**Issue by Villy21** [yujitach/MenuMeters#6]
Thank's for your work.

But when I install app from http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.zip
I get error "Could not load MenuMeters preference pane."

**Comment by benjaminboxler** [comment]
> 4. The System Preference might complain that it cannot be loaded. In that case please quit the System Preference once, and relaunch it. It should work.

From the [installation instructions](http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan).

**Comment by Villy21** [comment]
Simple quit System Preference did not help me.
But Mac OS restart solved the problem.
