### ISSUE TITLE
Feature Request: Display network speeds in Mbps (mega bits per sec)

### ISSUE THREAD

**Issue by sysfu** [yujitach/MenuMeters#61]
"To avoid confusion between bits and bytes, networking professionals always refer to network connection speeds in terms of bps (lowercase 'b') ratings."   source - https://www.lifewire.com/bits-per-second-kbps-mbps-gbps-818122

Please add support for displaying network speeds in Mbps if it's not too much trouble.

**Comment by yujitach** [comment]
I shouldn't be too hard but I don't have time. It would be a good learning experience to code in Objective-C for you to implement it yourself, have a look at https://github.com/yujitach/MenuMeters/blob/master/MenuExtras/MenuMeterNet/MenuMeterNetExtra.m 

I'm happy to merge a pull request if you make it.

**Comment by keiranharris** [comment]
I, like sysfu, am also a network guy, and id also love to have this small feature request added. I am a B.Sc in comp sci, so i do know how to code, so i may help you out here with the dev (ive just started a new job so am also very time poor right now). Ill put it on my todo list so i dont forget, but it will likely be 6 weeks away or so.

**Comment by dmthepm** [comment]
I'd also love to monitor in Mbps. Any movement on this?
