### ISSUE TITLE
disk menu doesn't show the APFS startup volume

### ISSUE THREAD

**Issue by daveyostcom** [yujitach/MenuMeters#63]
The disk menu doesn't show the APFS startup volume. It shows other, HFS+ volumes.
macOS 10.12 beta 4

**Comment by yujitach** [comment]
Thanks for letting me know. Could you post the output of "mount" from the command line? I'd like to check the file system time of an APFS volume. Is it apfs?

**Comment by daveyostcom** [comment]
```
40 Z% mount
/dev/disk2s1 on / (apfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk2s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk1 on /Volumes/SierraStartup (hfs, local, journaled)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
```
file system time? You mean the volume mtime?

**Comment by yujitach** [comment]
Thanks, and I meant the "file system type". Your info is very helpful; now I can fix it. Let me prepare a test binary for you...

**Comment by yujitach** [comment]
@daveyostcom , Could you try http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.6.zip ?

**Comment by daveyostcom** [comment]
Works. Thanks!

**Comment by yujitach** [comment]
Good to know it works. I'll release it soon.

**Comment by daveyostcom** [comment]
In MenuMeterDiskSpace.m you added a line with space indenting but the other lines are still indented with tabs.
