### ISSUE TITLE
Binaries unavailable

### ISSUE THREAD

**Issue by sam1am** [yujitach/MenuMeters#64]
The linked page where the binary can be downloaded is having issues. The page loads, but the image does not and the link to download results in an endless download attempt that never goes anywhere. It appears there are server issues. Is their a mirror?

**Comment by sam1am** [comment]
I found a mirror here: https://github.com/yujitach/MenuMeters/releases

**Comment by yujitach** [comment]
No.

**Comment by yujitach** [comment]
The server issue is now resolved.
