### ISSUE TITLE
Duplicate MenuMetersApp lines in Pref Pane → Accounts → Login Items

### ISSUE THREAD

**Issue by yujitach** [yujitach/MenuMeters#65]
MenuMetersApp seem to register itself multiple times to Login Items.
<img width="462" alt="2017-10-06 9 29 16" src="https://user-images.githubusercontent.com/5449811/31258249-da814c50-aa78-11e7-8557-6ca4e26424b6.png">

This does cause no actual harm but is not esthetically perfect. Should be resolved.

**Comment by emcrisostomo** [comment]
I've submitted a PR from [my fork][fork].

You can use also the DMG image of the [latest release][latest] if you'd like.

[fork]: https://github.com/emcrisostomo/MenuMeters
[latest]: https://github.com/emcrisostomo/MenuMeters/releases/latest

**Comment by yujitach** [comment]
merged #70.
