### ISSUE TITLE
http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ cannot be reached

### ISSUE THREAD

**Issue by adamdyga** [yujitach/MenuMeters#66]
Unfortunately the link http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ in the README file  doesn't work :(

**Comment by rantanplan77** [comment]
It works for me. Here's a PDF of the page:
[MenuMeters+for+OS+X+El+Capitan+10.11+and+later.pdf](https://github.com/yujitach/MenuMeters/files/1382253/MenuMeters.for.OS.X.El.Capitan.10.11.and.later.pdf)

**Comment by yujitach** [comment]
The server was off-line for a short while.
