### ISSUE TITLE
Trying to uninstall but the only option I get in the pop up menu is "remove from preference pane"

### ISSUE THREAD

**Issue by Zozr** [yujitach/MenuMeters#69]
Bit of an idiot here, how do I uninstall the application? In the system preferences the only option I have is "remove menu meters preference pane" but that just removes the icon from the preferences screen doesn't actually remove the app. 

Any help please?

https://imgur.com/lvJVCuy

**Comment by emcrisostomo** [comment]
@Zozr, the application is embedded in the preference pane: deleting it also deletes the application. If you're curious, the application is installed in the following path relative to the path of the preference pane:

```
${MM_PATH}/Contents/Resources/MenuMetersApp.app/Contents/MacOS/MenuMetersApp
```

**Comment by Zozr** [comment]
Thank you for replying. 

I have right clicked and deleted it and restarted my computer but each time the computer restarts it asks me to confirm if I want to open menu meters again, so it is still finding something and trying to open it despite removing it from the preference pane.

**Comment by yujitach** [comment]
The uninstallation instruction is given here: https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/
