### ISSUE TITLE
http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ is not accessible

### ISSUE THREAD

**Issue by ikuwow** [yujitach/MenuMeters#7]
Is the server down?

**Comment by steffenagger** [comment]
looks that way (you're not alone)

**Comment by yujitach** [comment]
Yeah the server is down...

**Comment by ranek** [comment]
Have you considered posting your binaries as releases on GitHub? This could alleviate some load on your server, if that's any concern.

**Comment by ikuwow** [comment]
OK, I can access now. http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/
