### ISSUE TITLE
Install fails on High Sierra

### ISSUE THREAD

**Issue by richseifert** [yujitach/MenuMeters#71]
I downloaded the install file for 1.9.6, but when I try to install it I get a message "Preferences Error: Could not load MenuMeters preference pane."

I'm sure this has been discovered before, but I didn't see it in the archive

**Comment by inwdragon** [comment]
I'm use version 1.9.1 on high sierra v10.13.1 is OK.

**Comment by isn0gud** [comment]
I am using 1.9.6 on 10.13.1 and it works fine. However, I installed it before upgrading from Sierra.

**Comment by mromaine** [comment]
JFYI, I installed 1.9.6 on a fresh install of 10.13.2 and it works perfectly.

**Comment by unnawut** [comment]
Installed 1.9.6 on a fresh install of 10.13.2 (High Sierra). Working perfectly.

**Comment by yujitach** [comment]
Should be OK. If it doesn't work, please try to uninstall & reboot & install.
