### ISSUE TITLE
"Duplicate" CPU meters on El Capitan 2x Xeon quad core

### ISSUE THREAD

**Issue by cudaboy71** [yujitach/MenuMeters#72]
![dupe_cpus](https://user-images.githubusercontent.com/34221157/33530883-766edc56-d83a-11e7-8692-a0de5e966076.jpg)

just downloaded the latest MM1.9.6 to be sure I'm up to date. I'm running OSX 10.11.16 on

Mac Pro (Mid 2010) 2 x 2.4 GHz Quad-Core Intel Xeon

I put Duplicate in quotes because they're not really dupes--every other processor is showing 0% regardless of load. So, they're really more like ghosts.

In any case, they shouldn't be there. This is an 8 core machine.

**Comment by myint** [comment]
This looks like #35.

**Comment by lambdaupb** [comment]
I'd guess the macOS scheduler is only using one hyper thread per core until all those are maxed out and only then starts using hyper threads.

You should load the system with something like prime95 with more workers than physical cores and confirm this is a bug in MenuMeters and not normal behaviour in macOS.

**Comment by onpaws** [comment]
If you have Xcode you can disable hyper threading with the included Instruments.app
![image](https://user-images.githubusercontent.com/182515/35071962-9b782886-fbda-11e7-82b6-5855c457f2b0.png)

The macOS scheduler is provided by xnu.
https://developer.apple.com/library/content/documentation/Darwin/Conceptual/KernelProgramming/scheduler/scheduler.html

**Comment by subotic** [comment]
I'm running the `1.9.7` on macOS Mojave (10.1.4) on a Mac Pro and every item is doubled.

![screenshot 2018-11-05 09 09 07](https://user-images.githubusercontent.com/400790/47985617-81349780-e0da-11e8-902e-6c5acc7032d9.png)

I have looked in the `PreferencePane` folder for duplicate MenuMeters, but there is only one running, as far as I can tell.

**Comment by lambdaupb** [comment]
@subotic this happens from time to time, there are just two MenuMeters processes running.
You can kill one in AcvtivityMonitor.

**Comment by yujitach** [comment]
This thread now discusses two distinct issues (#62 and #68). I'm going to close this one. Please report further problems there.
