### ISSUE TITLE
Why MenuMeters mounts himself?

### ISSUE THREAD

**Issue by ksuuk** [yujitach/MenuMeters#74]
Why MenuMeters mounts himself:

/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app  232Gi  132Gi   99Gi    58%   1393128 4293574151    0%   /private/var/folders/s8/j5wmql_n6tj8r9yc9jq1lrt00000gn/T/AppTranslocation/63C4BCA9-F74C-44A0-B37F-E185A7415C57

**Comment by yujitach** [comment]
This is a duplicate ot #41.
