### ISSUE TITLE
Opening PrefPane causes System Preferences Window to loose focus

### ISSUE THREAD

**Issue by fdanapfel** [yujitach/MenuMeters#75]
Before opening the MenuMeters PrefPane:
![system_preferences_before](https://user-images.githubusercontent.com/8794862/38453969-d6b61828-3a5e-11e8-9f48-095ac08f7dee.png)

After the PrefPane has been opened:
![system_preferences_after](https://user-images.githubusercontent.com/8794862/38453967-d22b4b34-3a5e-11e8-8f98-61564348a0c8.png)

The only way to get the System Preferences Window back to the normal state is by completely closing System Preferences and reopening.

I'm running Mac OS X 10.12.6 and use the fork of MenuMeters from https://github.com/emcrisostomo/MenuMeters

**Comment by yujitach** [comment]
In my case I can just click the Preferences Window and then it regains focus. If the same doesn't work for you, I guess it's a problem of emcrisostomo's version, and you need to ask him instead.
