### ISSUE TITLE
Hight Sierra 10.13.6 blocks out Menumeters 1.9.6

### ISSUE THREAD

**Issue by ogattaz** [yujitach/MenuMeters#78]
Menumeters 1.9.6 doesn't start after updating my MacBook from  Hight Sierra 10.13.5 to 10.13.6

**Comment by onpaws** [comment]
I've been on 1.9.6 for a while now and on macOS 10.13.6 its working fine for me.
![image](https://user-images.githubusercontent.com/182515/42875079-06f43780-8a83-11e8-9557-dcb111b9c343.png)

You might consider double checking your quarantine settings for MenuMeters. 
Typically you can clear the Gatekeeper quarantine with `xattr -c` - suggest Googling it a bit.
