### ISSUE TITLE
Upon installing the pref pane: Could not load MenuMeters preference pane.

### ISSUE THREAD

**Issue by avmedrano** [yujitach/MenuMeters#8]
![installingmenumeters1 9prefpane](https://cloud.githubusercontent.com/assets/13355249/10268504/28d3b296-6a91-11e5-9519-395d896ec65b.jpg)

**Comment by princefisher** [comment]
From the installation instructions:
4. The System Preference might complain that it cannot be loaded. In that case please quit the System Preference once, and relaunch it. It should work.

**Comment by avmedrano** [comment]
Thank you so much!  I did not realize El Cap would reset my preferences
that way.
