### ISSUE TITLE
Multiple MenuMetersApp processes on startup

### ISSUE THREAD

**Issue by canadiannomad** [yujitach/MenuMeters#81]
Likely something went wrong when I was upgrading (from a very old version).. but whenever I reboot my machine I get multiple MenuMetersApp processes and associated meters running.  I then go in and kill one, and everything is good.. But my question is, what is the best way to make sure it only runs once?
Thanks!

**Comment by luckman212** [comment]
Check **System Preferences > Users & Groups > Login Items** and make sure there are no duplicates?

**Comment by yujitach** [comment]
This is a duplicate of #68, and is a pretty common problem people seem to encounter. We should better do something.

**Comment by canadiannomad** [comment]
Thanks @luckman212 that was it.. Maybe an update to docs.. or the updater?

**Comment by luckman212** [comment]
Yes this is an old problem. I don't know how to fix it unfortunately (other than manually as above). I'll leave that to @yujitach or anyone who can help.
