### ISSUE TITLE
Mojave: External monitor attached cause icons to flicker (in dark mode)

### ISSUE THREAD

**Issue by svenbergryen** [yujitach/MenuMeters#84]
In Dark Mode, and when I'm using an external monitor, the MenuMeters icons turn white and start to flicker every time they're updated. They're shown in color without any flickering when I'm using just the internal retina display.

The flickering is so annoying that I've had to hide the menu bar when not used.

**Comment by luckman212** [comment]
Have you tried [v1.9.7](https://github.com/yujitach/MenuMeters/releases/tag/1.9.7) ?
Is that still a problem?

**Comment by svenbergryen** [comment]
Seems like Apple fixed their bug. I also reported it to them.

**Comment by yujitach** [comment]
Good to know it's fixed! Thanks for reporting.
