### ISSUE TITLE
Only Chinese for v1.9.7 

### ISSUE THREAD

**Issue by gfoligna** [yujitach/MenuMeters#86]
Hi there!

Just installed newer version 1.9.7 and got all in Chinese as you might see at the screencaps.
![menumeters-chinese2](https://user-images.githubusercontent.com/6373129/46088517-ee234c00-c182-11e8-9b79-0c6df7943706.png)
![menumeters-chinese](https://user-images.githubusercontent.com/6373129/46088518-eebbe280-c182-11e8-8dc1-018183b49f0b.png)

I got v1.9.6 installed previously (if it helps).

MacOS High Sierra (10.13.6)
Macbook Pro 15'' Early 2011

**Comment by gfoligna** [comment]
It works like a charm now.
Thanks for fixing! 😺

**Comment by yujitach** [comment]
You're welcome; thank you again for catching and reporting the bug so quickly.
