### ISSUE TITLE
Make the colors of charts and numbers to support dark theme 

### ISSUE THREAD

**Issue by lijunle** [yujitach/MenuMeters#88]
I like the default colors. However, when I use the dark theme, the default colors are too dark. Is there any pattern to *auto convert* the existing color to brighter in dark theme?

**Comment by gfoligna** [comment]
I'm thinking something about a color inverter. Like this: http://www.mattlag.com/scripting/hexcolorinverter.php

Am I way too far from the question?

**Comment by yujitach** [comment]
I sometimes receive emails asking for a better support of the dark mode. As suggested above, two possible ways out are:
- auto invert the color
- enhance the pref pane UI so that the colors for the light mode and the dark mode can be chosen separately.

**Comment by yujitach** [comment]
I'm merging this with another newer issue #204 which discusses basically the same usability problem.
