### ISSUE TITLE
Command-Drag for Re-ordering of the icons isn't working.

### ISSUE THREAD

**Issue by Abhinav-Biswas** [yujitach/MenuMeters#9]
I am able to drag and re-order other system icons in menu bar like date, power status, wifi, volume etc. but not the menumeter icons.

**Comment by yujitach** [comment]
Please read the explanation at the bottom of http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/ for the background why.  The original author of MenuMeters is now working on a version on El Capitan with Command-Dragging, so please stay tuned.
