### ISSUE TITLE
brew cask install menumeters returns error. 

### ISSUE THREAD

**Issue by chetanpm** [yujitach/MenuMeters#91]
Chetans-MacBook-Pro:~ chetanpm$ brew cask install menumeters
==> Satisfying dependencies
Error: Cask menumeters depends on macOS release <= 10.10, but you are running release 10.14.

**Comment by yujitach** [comment]
I don't know much about brew cask. Could you elaborate? My binary is compiled on 10.14, but the depolyment target is set to 10.10. I think it's a problem on the maintainer of brew cask, not mine.

**Comment by chetanpm** [comment]
I saw your comment on latest release: "The way I released 1.9.7 below confused Homebrew Cask. This new release, 1.9.7bis, is just to de-confuse it. The attached binary is the same one as the release 1.9.7.”
I thought it might be related to the error I was getting.

**Comment by yujitach** [comment]
I don't think so. My comment was about https://github.com/Homebrew/homebrew-cask/pull/52706 . Please test if my binary works by directly downloading it from my latest release. If it works, then it's a problem on homebrew cask, so please report it to maintainers of homebrew cask, not to me.

**Comment by chetanpm** [comment]
The binary from direct download works well. Thank you :)

**Comment by ynovytskyy** [comment]
@chetanpm The following Homebrew command works
`brew cask install yujitach-menumeters`

**Comment by chetanpm** [comment]
@ynovytskyy Now it works. Thank you :)
