### ISSUE TITLE
Feature Request: Stack Cores in Graph mode

### ISSUE THREAD

**Issue by eejd** [yujitach/MenuMeters#96]
Especially on laptops, when using graph for CPU history display, stacking cores or virtual cores would help save menu real estate without sacrificing access to the information. Especially on retina displays, this should be possible with enough granularity to be useful. I assume it wouldn't be too hard to calculate the widget location and do this. However, before embarking on looking into the code, I wanted to see if it would be trivial to code for someone who knows the code base or if there is some reason it isn't actually easy to implement.

**Comment by yujitach** [comment]
Indeed it’s not too hard and would be useful. But I don’t have the time right now. 

In any case, how would you want to combine the graphs? At present, each CPU core has a graph with multiple colors. Keeping all these info would result in a very complicated graph...

**Comment by gubikmic** [comment]
Is it possible to just disable the virtual cores?

**Comment by emcrisostomo** [comment]
@gubikmic, you can set MenuMeters to only display the averages of all the CPUs.

**Comment by yujitach** [comment]
I think recent enhancements address the issue.
