### ISSUE TITLE
Compressed Color Picker Missing in 1.9.7

### ISSUE THREAD

**Issue by bdarfler** [yujitach/MenuMeters#99]
In 1.9.6 I see a color option for Compressed memory.
![screen shot 2019-02-11 at 12 02 52 pm](https://user-images.githubusercontent.com/197776/52581967-12ae5680-2dfa-11e9-8d1e-88b89040ced4.png)

In 1.9.7 it is gone.
![image](https://user-images.githubusercontent.com/197776/52581934-02967700-2dfa-11e9-9718-c7e61d808c49.png)

There are still 4 colors that show up in the menu bar while running both 1.9.6 and 1.9.7
![screen shot 2019-02-11 at 12 40 02 pm](https://user-images.githubusercontent.com/197776/52582078-543f0180-2dfa-11e9-8df5-b973ff147a97.png)

**Comment by yujitach** [comment]
This should be finally fixed in the new version 2.0.3, available via auto update
